### ISSUE TITLE
Versioning of Schemas

### ISSUE THREAD

**Issue by sebbader** [admin-shell-io/aas-specs#12]
The schemas follow the versioning scheme of 'Details of the AAAS', for instance, are we currently working on version 3.0 RC01. How can we reflect that in our repo?

Let me make two suggestions for the beginning:

1. Let's add versions as top-level folders
2. Let's create releases for each version/revision and maintain only the latest revision as the source in the repo.

What's your opinion, @Manu3756 , @JoergWende, @BirgitBoss ?

**Comment by BirgitBoss** [comment]
I would go with 2: make releases for every official release or bugfix. The master branch should be the newest release. Working version should be on a working branch.

**Comment by sebbader** [comment]
That's also my preference. I just created a `develop` branch for the working commits. Then let's do the following: `master` is protected, nobody is allowed to push directly. Merges are only executed at the release of a new version, after approval by the UAG AAS or Steering Committee, which directly triggers a (manual) creation of a new release.

`develop` can be protected or not. Still, content only in `develop` must not be used by productive systems.

**Comment by sebbader** [comment]
@mristin: Does that fit to the conventions you formulated when creating the repo?

**Comment by mristin** [comment]
@sebbader We haven't really put up any convention regarding the branches. Personally, I find your approach fine!

**Comment by sebbader** [comment]
We have an agreement, and this issue has been stale for a very long time. Therefore I am closing it.
