### ISSUE TITLE
Plural form of properties in RDF ontology

### ISSUE THREAD

**Issue by kenwenzel** [admin-shell-io/aas-specs#163]
The RDF ontology defines plural forms of some properties like `submodelElements` as can be seen here:
https://github.com/admin-shell-io/aas-specs/blob/e7fe85877c616838a59e17b1f90b038372ca9362/schemas/rdf/rdf-ontology.ttl#L2366

The examples use properties in singular form:
https://github.com/admin-shell-io/aas-specs/blob/e7fe85877c616838a59e17b1f90b038372ca9362/schemas/rdf/examples/Submodel_SubmodelElement_Example.ttl#L69

Probably the plural forms are wrong as ontologies usually define singular forms for multi-valued properties.

**Comment by mristin** [comment]
Hi @kenwenzel ,
Thanks for submitting the issues!

The reason behind the plural forms is that the code in  https://github.com/admin-shell-io/java-model is automatically generated based on it and thus the properties need to coincide with the JSON and XML schema.

The examples are indeed outdated and we are preparing the new ones for V3RC02.

**Comment by mristin** [comment]
Please have a look at the branch https://github.com/admin-shell-io/aas-specs/tree/draft-V3RC02-schemas for the latest development.

@changqin26 FYI

**Comment by kenwenzel** [comment]
Thank you for the quick response. The properties are indeed in singular form now. That is good.

Do you think it is also possible to move all properties into the AAS namespace as mentioned in issue #43 for V3RC02? This would really simplify the usage of the RDF syntax.
If property ranges are an issue then OWL local property restrictions can be used to express them.
The attributes in the XML serialization are also not in different namespaces.

**Comment by mristin** [comment]
@kenwenzel I'm closing the issue for now as it seems to be fixed. Please re-open, or better re-create a concrete issue for V3RC02.
