### ISSUE TITLE
Wrong namespace for properties in RDF examples

### ISSUE THREAD

**Issue by kenwenzel** [admin-shell-io/aas-specs#164]
One or more of the RDF examples solely use properties in the namespace `https://admin-shell.io/aas/3/0/RC01/`.
Either the examples are wrong or the AAS RDF ontology is wrong as the latter defines properties in the namespace of the related entities.

One [example](https://github.com/admin-shell-io/aas-specs/blob/e7fe85877c616838a59e17b1f90b038372ca9362/schemas/rdf/examples/Submodel_SubmodelElement_Example.ttl#L27) uses `https://admin-shell.io/aas/3/0/RC01/idShort` while the ontology defines the property as `https://admin-shell.io/aas/3/0/RC01/Referable/idShort`.

This is also related to #43

Please let me know how I can help and how we should go forward. It seems that the development of the RDF models has been stalled for a while.

**Comment by mristin** [comment]
@changqin26 can you please have a look? This is also relevant for V3RC02.

**Comment by changqin26** [comment]
@mristin, the examples in the branch `feature/RdfUpdate` are correct. I am wondering when you merged this branch to the` master` 28 days ago, why the examples in the `feature/RdfUpdate` branch are not merged into `master` at the same time? Under the `master` branch, Examples folder is updated 3 months ago.

**Comment by mristin** [comment]
@changqin26 wrote:
> the examples in the branch feature/RdfUpdate are correct. I am wondering when you merged this branch to the master 28 days ago, why the examples in the feature/RdfUpdate branch are not merged into master at the same time?

I'll have a closer look at it today.

**Comment by mristin** [comment]
@kenwenzel  @changqin26 thanks for spotting the problem! I forgot to check out the examples from `feature/RdfUpdate`. I merged them a second ago to the master in the pull request #165.

@kenwenzel could you please have another look at the most recent examples in the master branch? Mind that they are meant for the V3RC01 of the meta-model, *not* V3RC02.

**Comment by kenwenzel** [comment]
Thank you @changqin26  and @mristin. The examples look correct now. But as can be seen it's simply a mess to express an AAS in RDF with properties in so many different namespaces (#43).

**Comment by mristin** [comment]
@kenwenzel I'll close this issue for now as the examples are fixed. Let's continue the discussion about the namespaces in #43.
