### ISSUE TITLE
XML-Schema: Failure in extension_t

### ISSUE THREAD

**Issue by TorbenD** [admin-shell-io/aas-specs#17]
According to the specification an Extension-Objekt the attribute "RefersTo" has a multiplizity of zero or one. In the xml-schema the multiplizity is one to any. 

Following proposal:
Change aas:references_t to reference_t in extension_t

**Comment by JoergWende** [comment]
accepted - will be changed in V3.0.1RC1 
J.

**Comment by JoergWende** [comment]
Fixed
