### ISSUE TITLE
Bug - SupplementalSemanticId has cardinality 0..* not 0..1

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#189]
SupplementationSemanticId has cardinality 0..* not 0..1		

                                    <supplementalSemanticIds>
						<reference>
							<type>GlobalReference</type>
							<keys>
								<key>
									<type>GlobalReference</type>
									<value>something_random_e14ad770</value>
								</key>
							</keys>
						</reference>
					</supplementalSemanticIds>

==>

                                <supplementalSemanticIds>
                                    <supplementalSemanticId>
						<reference>
							<type>GlobalReference</type>
							<keys>
								<key>
									<type>GlobalReference</type>
									<value>something_random_e14ad770</value>
								</key>
							</keys>
						</reference>
					</supplementalSemanticId>
                                 <supplementalSemanticIds>

same for JSON and probably rdf as well

**Comment by mristin** [comment]
This refers to the branch https://github.com/admin-shell-io/aas-specs/tree/draft-V3RC02-schemas, correct?

**Comment by mristin** [comment]
Hi Birgit,
`SupplementalSemanticId` is indeed modeled as a list; sorry, I didn't read your examples careful enough. The first example in your comment https://github.com/admin-shell-io/aas-specs/issues/189#issue-1285700413 is correct, the second one is incorrect.

We put the model type in the tag (`reference` in this case), not the singular form of the property name.

This is the relevant part of the schema:
```
      <xs:element name="supplementalSemanticIds" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="reference" type="reference_t" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
```

**Comment by BirgitBoss** [comment]
Then my expectation would have been:

                            <supplementalSemanticIds>
                                <supplementalSemanticId>
					        <type>GlobalReference</type>
						<keys>
							<key>
								<type>GlobalReference</type>
								<value>something_random_e14ad770</value>
							</key>
						</keys>
				</supplementalSemanticId>
                             <supplementalSemanticIds>

is this you common pattern to not use the attribute names but the type names? In former version I think we  therefore had both (as in my second example):

<supplementalSemanticIds>
                                <supplementalSemanticId>
					<reference>

**Comment by mristin** [comment]
@BirgitBoss: As I already mentioned, we put the type name in the element tag and not the singular of the property. This is much easier to implement, and avoids all sorts of problems (*e.g.*, works in situations where we have to perform a dispatching in case of abstract classes, no ill-defined singular/plural forms *etc.*).

Please see this example: https://github.com/admin-shell-io/aas-specs/blob/9620e04bb2197943442002f4dd81da08e98ad9f0/schemas/xml/examples/generated/blob/complete.xml#L42-L52
