### ISSUE TITLE
Terminology of 'operation' in DAAS part 2

### ISSUE THREAD

**Issue by mmarseu** [admin-shell-io/aas-specs#19]
This is a minor piece of feedback for the *Details of the Asset Administration Shell - Part 2* document.
I find the use of the term 'operation' for API operations (e.g. *GetAssetAdministrationShell*) highly confusing, given that it also signifies a metamodel concept in part 1. 

I'd be in favor of any other synonym like method.

**Comment by BirgitBoss** [comment]
I share your concern. The group working on the API was aware of the confusion that might arise and therefore always adds a prefix like "API Operation" "Interface Operation". The reason for using the term "operation" in the API specification is that the interface concept is based on an existing DIN Specification and Part 1 of the AAS was released already earlier.

**Comment by sebbader** [comment]
We have added this topic into the findings list of the API task force. It will require a longer discussion, also regarding the - still valid - reasons why 'API Operation' and 'Interface Operation' have been selected in the first place. I will therefore close the issue now as we won't fix it with the next release but will put it back on the agenda later.
