### ISSUE TITLE
minim manually created AAS should contain globalAssetId or a specific Asset Id

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#190]
There is the implicit constraint that either a globalAssetId or at least one specificAssetId needs to be available. This should be made explicit in next release of Part 1

since this example is manually created it should contain a globalAssetId

https://github.com/admin-shell-io/aas-specs/blob/draft-V3RC02-schemas/schemas/xml/examples/manual/asset_administration_shell/minimal_asset_administration_shell.xml

Compare to
https://github.com/admin-shell-io/aas-specs/blob/draft-V3RC02-schemas/schemas/xml/examples/generated/specificAssetId/minimal.xml
Here, a specific asset ID is part of

**Comment by mristin** [comment]
Does this constraint already exists in text in the book for V3RC02?

**Comment by mristin** [comment]
Otherwise, similar to #191, this is a valid *minimal* example according to the book V3RC02, isn't it?

**Comment by mristin** [comment]
Fixed by #196.
