### ISSUE TITLE
Example manually created Concept Description 

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#191]
Since this is a manually created example it should contain a data specification. This shall be added as a constraint in Part 1. Without data specification concept description do not make  sense.

https://github.com/admin-shell-io/aas-specs/blob/draft-V3RC02-schemas/schemas/xml/examples/manual/concept_description/minimal_concept_description.xml

Add data specification for properties

**Comment by mristin** [comment]
Do I get this right: according to the book V3RC02 this is a valid *minimal*  example, though?

**Comment by mristin** [comment]
Fixed by #196.
