### ISSUE TITLE
Bug - idShort required for property according constraint AASd-117

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#192]
See manually created example for minimal property:

https://github.com/admin-shell-io/aas-specs/blob/draft-V3RC02-schemas/schemas/xml/examples/manual/submodels/property/minimal_property.xml

                <property>
                    <valueType>xs:boolean</valueType>
                </property>

idShort is required accoding to constraint 
Constraint AASd-117: idShort of non-identifiable Referables not equal to SubmodelElementList shall be specified (i.e. idShort is mandatory for all Referables except for SubmodelElementLists and all Identifiables).

**Comment by mristin** [comment]
Thanks! I think I forgot to include the verification on manual examples.

**Comment by mristin** [comment]
I'll remove the manually written examples since they are obviously unmaintainable.

This will also affect issues #191 and #190.

**Comment by mristin** [comment]
Fixed by #196.
