### ISSUE TITLE
Complete xml Example for V3.0RC02 - Embedded Data Specification Approach not implemented

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#195]
https://github.com/admin-shell-io/aas-specs/blob/draft-V3RC02-schemas/schemas/xml/examples/generated/submodel/complete.xml

In the past we followed the embedded data specification approach, here, only the references to data spec. are contained but not the content.

See chapter 9.2.5 in Part 1 of Details of the Asset Administation Shell

![grafik](https://user-images.githubusercontent.com/59824205/175944136-1664da8a-92d2-48a9-b346-0fb2d122b9fb.png)

**Comment by mristin** [comment]
This can not be implemented in a schema. Please contact @g1zzm0  off-line.

**Comment by mristin** [comment]
(Just a small clarification: this is not implementable at least not for a transpiled schema.)

**Comment by BirgitBoss** [comment]
Please have a look at former versions of the schema how this was implemented. I am sure it also works for a transpiled schema because it is an easy implementation pattern.

**Comment by mristin** [comment]
As we can not implement embeddable data specifications, I am closing this issue. Please open a separate issue once the data specifications are generated as separate files if you have comment on those.
