### ISSUE TITLE
XML: XSD should use xs:all instead of xs:sequence

### ISSUE THREAD

**Issue by TorbenD** [admin-shell-io/aas-specs#20]
The XSD currently uses xs:sequence to define attributes of types. This requires the children of elements in XML documents to be in the exact same order as defined in the XSD, which results in the unnecessary work of re-ordering code-blocks in serialization adapters. Changing xs:sequence to xs:all would remove this limitation, allowing children in any order to be valid against the schema.

**Comment by mristin** [comment]
Closing as we agreed in internal discussion to enforce the order of the attributes in the XML de/serialization for readability.
