### ISSUE TITLE
ValueOnly Schema for JSON

### ISSUE THREAD

**Issue by sebbader** [admin-shell-io/aas-specs#203]
Part 2 introduces a ValueOnly and MetaDataOnly Serialization, including respective JSON schemes. We need to:

- [ ] add the ValueOnly schema also to the JSON folder, 
- [ ] add the MetaDataOnly schema also to the JSON folder, 
- [ ] extend the README file of the folder to explain their usage and intention.

**Comment by sebbader** [comment]
@constantinziesche will create a PR for this issue.

**Comment by mristin** [comment]
@sebbader please don't forget to put all this on the https://github.com/admin-shell-io/aas-specs/tree/draft-V3RC02-schemas branch.

**Comment by g1zzm0** [comment]
Release and adjustment have already been done with the release
