### ISSUE TITLE
JSON: Add DataElement to Schema

### ISSUE THREAD

**Issue by TorbenD** [admin-shell-io/aas-specs#21]
The JSON schema currently doesn't have any type for DataElements. We suggest to add this missing type, so schema validators can spot incorrectly placed SubmodelElements, e.g. where a DataElement is expected.
Additionally, the XML Schema Definition has such a type, so adding this type would improve the consistency between the two schemas.

**Comment by Manu3756** [comment]
@TorbenD  
is this still valid? for V3.0RC02?
@mristin 
what is your opinion here?

**Comment by TorbenD** [comment]
I would say: Yes. Cause we need it for AnnotatedRelationshipElements where annotations are a list of DataElements ;-)

**Comment by mristin** [comment]
LGTM. As a rule: whenever you use a type which has one or more concrete descendants, the model type must be indicated.

A side remark: this should be automatically handled by the generator for V3RC02.

**Comment by mristin** [comment]
Closing as already fixed in the draft of V3RC02.
