### ISSUE TITLE
xml V3.0RC02 Type of Property/value not correct

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#210]
https://github.com/admin-shell-io/aas-specs/tree/draft-V3RC02-schemas
xml schema:

Type of Propery/value is value „any xsd atomic type as specified via DataTypeDefXsd“ according to specification V3.0RC02 and not string (https://industrialdigitaltwin.org/wp-content/uploads/2022/06/DetailsOfTheAssetAdministrationShell_Part1_V3.0RC02_Final1.pdf)

Note: In previous versions of the spec the type was anySimpleType

Note: for JSON serialization string was accepted as type

**Comment by mristin** [comment]
Closing since addressed in #219.
