### ISSUE TITLE
xml V3.0RC02 supplementalSemanticIds etc. - how to deal with 0..* cardinality bug

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#211]
https://github.com/admin-shell-io/aas-specs/tree/draft-V3RC02-schemas
xml schema:
(as generated as example https://raw.githubusercontent.com/admin-shell-io/aas-specs/draft-V3RC02-schemas/schemas/xml/examples/generated/submodel/complete.xml):

			<supplementalSemanticIds>
				<reference>
					<type>GlobalReference</type>
					<keys>
						<key>
							<type>GlobalReference</type>
							<value>something_random_c2c84a40</value>
						</key>
					</keys>
				</reference>
			</supplementalSemanticIds>

From my understanding it should look like this (supplementalSemanticId instead of reference):

			<supplementalSemanticIds>
				<supplemenatlSemanticId>
					<type>GlobalReference</type>
					<keys>
						<key>
							<type>GlobalReference</type>
							<value>something_random_c2c84a40</value>
						</key>
					</keys>
				</supplementalSemanticId>
			</supplementalSemanticIds>

Serialiaztion Rule from V3.0RC01:
https://github.com/admin-shell-io/aas-specs/tree/master/schemas/xml

Rule 4:
Repeating elements and their types will get the same names of their instances in plural. Exception: SubmodelElementCollection, here the name remains “value”. If the element has a cardinality of n>1 a parent element will be used with the name of the element in plural. For example, each element in the aggregation assets needs to be an asset.

**Comment by BirgitBoss** [comment]
Similar here:
https://github.com/admin-shell-io/aas-specs/blob/draft-V3RC02-schemas/schemas/xml/examples/generated/conceptDescription/complete.xml

			<isCaseOf>
				<reference>
					<type>GlobalReference</type>
					<keys>
						<key>
							<type>GlobalReference</type>
							<value>something_random_8fc8a489</value>
						</key>
					</keys>
				</reference>

**Comment by BirgitBoss** [comment]
Same here:

					<inputVariables>
						<operationVariable>
							<value>
								<blob>
									<contentType>application/something-random</contentType>
								</blob>
							</value>
						</operationVariable>

although it looks good but the serialization rule would lead to. This was the rule

					<inputVariables>
						<inputVariable>
							<value>
								<blob>
									<contentType>application/something-random</contentType>
								</blob>
							</value>

**Comment by BirgitBoss** [comment]
proably also similar to https://github.com/admin-shell-io/aas-specs/issues/213

**Comment by mristin** [comment]
@BirgitBoss please see the explanation at https://github.com/admin-shell-io/aas-specs/issues/213#issuecomment-1232841211.
