### ISSUE TITLE
xml V3.0RC02: dataSpecificationContent not conformant to spec

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#213]
https://github.com/admin-shell-io/aas-specs/tree/draft-V3RC02-schemas

xml schema:
(as generated as example https://raw.githubusercontent.com/admin-shell-io/aas-specs/draft-V3RC02-schemas/schemas/xml/examples/generated/submodel/complete.xml):

I know it was like this before, however, it is not like specified

					<dataSpecificationContent>
						<dataSpecificationIec61360>
							<preferredName>
								<langString>
									<language>en</language>
									<text>something_random_0796a3b4</text>
								</langString>
							</preferredName>
							<value>something_random_09a283e0</value>
						</dataSpecificationIec61360>
					</dataSpecificationContent>

In my understanding it should be

					<dataSpecificationContent>
							<preferredName>
								<langString>
									<language>en</language>
									<text>something_random_0796a3b4</text>
								</langString>
							</preferredName>
							<value>something_random_09a283e0</value>
					</dataSpecificationContent>

The information that it is IEC6136 template is within

					<dataSpecification>
						<type>GlobalReference</type>
						<keys>
							<key>
								<type>GlobalReference</type>
								<value>something_random_27587fef</value>
							</key>
						</keys>
					</dataSpecification>

I understand that this might not be wanted but for

			<submodelElements>
				<blob>
					<idShort>some_id_short_10b21b1b</idShort>
					<contentType>application/something-random</contentType>
				</blob>
			</submodelElements>

we also do not have (any longer)

			<submodelElements>
                          <submodelElement>
				<blob>
					<idShort>some_id_short_10b21b1b</idShort>
					<contentType>application/something-random</contentType>
				</blob>
                           </submodelElement>
			</submodelElements>

Perhaps serialization rules for aggreation and composition are different?

**Comment by mristin** [comment]
Hi @BirgitBoss ,
We do not handle the model type on case-by-case basis. It's always the same algorithm:
* In JSON we put it in `modelType` property,
* In XML, we put it in the name of the element. Moreover, each attribute is represented as an element. In case of lists, the items are enclosed in the elements designating the model type.

That is why you see first `dataSpecificationContent` (attribute) with a nested `dataSpecificationIec61360` (model type).

I'll document this in the readme.

**Comment by BirgitBoss** [comment]
This is what I expected, this is why are wondered because dataSpecificationContent (attribute) is not part of a list, its parent is EmbeddedDataSpecification with cardinality 0..1

The list is 

    embeddedDataSpecifications
      embeddedDataSpecification1
            dataSpecification
            dataSpecificationContent
      embeddedDataSpecification2
            dataSpecification
            dataSpecificationContent

There is a bug in the specification, because cardinality of HasDataSpecification/embeddedDataSpecification is not 0..1 but 0..*

**Comment by mristin** [comment]
@BirgitBoss please re-visit the schema and the examples. It is indeed implemented as expected -- the cardinality of embedded data specifications is `0..*`.

**Comment by mristin** [comment]
Documented in #224, closing.

**Comment by BirgitBoss** [comment]
Documentation is in file containing the serialization rules for xml schema, chapter "Instances Serialized with Discriminator"
