### ISSUE TITLE
Question w.r.t. Enumeration Values Capital Letters?

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#214]
https://github.com/admin-shell-io/aas-specs/tree/draft-V3RC02-schemas

xml schema:
(as generated as example https://raw.githubusercontent.com/admin-shell-io/aas-specs/draft-V3RC02-schemas/schemas/xml/examples/generated/submodel/complete.xml):

e.g. https://github.com/admin-shell-io/aas-specs/blob/draft-V3RC02-schemas/schemas/xml/examples/generated/basicEventElement/complete.xml

					<direction>OUTPUT</direction>
					<state>OFF</state>

In the specification the enumeration states: 
     input/output or 
      on/off 
as values. Are all enumeration values converted to Capital Letters? Is this a general rules for xml serialization?

For assetKind for example it is not like this:
https://github.com/admin-shell-io/aas-specs/blob/draft-V3RC02-schemas/schemas/xml/examples/generated/assetInformation/complete.xml
		<assetKind>Instance</assetKind>

**Comment by mristin** [comment]
Closing since addressed in #219.
