### ISSUE TITLE
xml V3.0RC02 example for environment missing

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#215]
I love the examples! I miss the (complete and minimal) example for environment

https://github.com/admin-shell-io/aas-specs/tree/draft-V3RC02-schemas/schemas/xml/examples/generated

**Comment by mristin** [comment]
Thanks! This was a bug in my script (the examples are available at https://github.com/aas-core-works/aas-core3.0rc02-testgen/tree/main/test_data/Xml/SelfContained/Expected/environment, I just need to copy them).

**Comment by mristin** [comment]
Closing since addressed in #219.
