### ISSUE TITLE
xml V3.0RC02 examples valid?

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#216]
https://github.com/admin-shell-io/aas-specs/blob/draft-V3RC02-schemas/schemas/xml/examples/generated/conceptDescription/complete.xml

                <administration/>

is generated because none of its attributes is mandatory. However, this leads to an invalid generated xml file, doesn't it? As far as I remember empty tags are not allowed any longer.

This should at least be mentioned in the Readme explaining that examples can be found and how to deal with them.

**Comment by mristin** [comment]
@BirgitBoss empty tags are indeed allowed (an instance without any of the attributes specified). What is disallowed are the empty lists and empty strings.
