### ISSUE TITLE
xml V3.0RC02 isCaseOf of ConceptDescription

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#217]
https://github.com/admin-shell-io/aas-specs/blob/draft-V3RC02-schemas/schemas/xml/examples/generated/conceptDescription/complete.xml

			<isCaseOf>
				<reference>
					<type>GlobalReference</type>
					<keys>
						<key>
							<type>GlobalReference</type>
							<value>something_random_8fc8a489</value>
						</key>
					</keys>
				</reference>
			</isCaseOf>

The cardinality of isCaseOf is 0..*, typically in this case an "s" is added:

  <isCaseOfs> 
      <isCaseOf>...

of course this is not valid English. So either it is an exception for a serializationRule, e.g. isCaseOfSet or we should rename it in the next version of the specification?

Compare also to https://github.com/admin-shell-io/aas-specs/issues/211 that focusses on the <reference> itself.

**Comment by mristin** [comment]
We decided to have correct English throughout the schema. This is a complete list of exceptions for V3RC02:
https://github.com/aas-core-works/aas-core-meta/blob/1df1729d364367ca460e43a40b19d9d3edc19930/tests/test_v3rc2.py#L1122

**Comment by BirgitBoss** [comment]
These exceptions need to part of the Readme with the serialization rules as well.

**Comment by mristin** [comment]
Added to JSON readme.
