### ISSUE TITLE
XML: Remove unnecessary wrapper elements

### ISSUE THREAD

**Issue by TorbenD** [admin-shell-io/aas-specs#22]
The current version of the schema (v3.0 RC01) has unnecessary wrapper elements around each Submodel Element and Data Element.

Submodel Element
```
<submodelElements>
    <submodelElement> <!-- this is unnecessary -->
       <entity/>
    </submodelElement>
    <submodelElement> <!-- this is unnecessary -->
        <property/>
    </submodelElement>
    [...]
</submodelElements>
```
We suggest the removal of the wrapper element:
```
<submodelElements>
    <entity/>
    <property/>
    [...]
</submodelElements>
```

Data Element
```
<annotations>
    <dataElement> <!-- this is unnecessary -->
        <property/>
    </dataElement>
    <dataElement> <!-- this is unnecessary -->
        <range/>
    </dataElement>
    [...]
</annotations>
```
Again, we suggest the removal of the wrapper element:
```
<annotations>
    <property/>
    <range/>
    [...]
</annotations>
```

**Comment by JoergWende** [comment]
will take a look later 
J.

**Comment by JoergWende** [comment]
wrapper elements had been introduced to reflect cardinalities of 'unbounded'

**Comment by BirgitBoss** [comment]
I would agree to remove the tag for the abstract class submodelelement

**Comment by mristin** [comment]
Closing as this is a documentation issue; see this comment which addresses a very similar issue: https://github.com/admin-shell-io/aas-specs/issues/213#issuecomment-1232841211
