### ISSUE TITLE
Create New Folder for Verbs etc.

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#238]
The file
https://github.com/BirgitBoss/aas-specs/blob/draft-V3RC02-schemas/AdditionalVerbsInImperativeMood.txt
is very irritating. I assume this is about PR and how to formulate the title of the PR?

Please create a new folder for adding files that belong to contribution guideline. Should not be on top level folder

**Comment by mristin** [comment]
I'll move it to `continuous_integration/` folder.

**Comment by mristin** [comment]
Fixed by #239 .
