### ISSUE TITLE
XML Examples Readme still contain TODO

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#241]
https://github.com/admin-shell-io/aas-specs/tree/master/schemas/xml/examples

First paragraph says "TODO [..]" However, I think the status is "Done" ? Just remove sentence

**Comment by mristin** [comment]
@BirgitBoss thanks for spotting it! I'll fix it today or tomorrow. I'll just document that the examples were generated automatically.
