### ISSUE TITLE
xs:dateTime pattern doesn't allow timezone information

### ISSUE THREAD

**Issue by jkhsjdhjs** [admin-shell-io/aas-specs#244]
The pattern that is currently used to validate `xs:dateTime` values doesn't allow timezones. For example, it prohibits `2022-11-12T23:50:23.000789+01:00` (UTC+1) while `2022-11-12T23:50:23.000789Z` (no timezone / UTC) works fine. [DotAAS V3.0RC02](https://www.plattform-i40.de/IP/Redaktion/EN/Downloads/Publikation/Details_of_the_Asset_Administration_Shell_Part1_V3.pdf?__blob=publicationFile) states on page 99 that timezone information is allowed for `xs:dateTime`, and the [XML Schema specification](https://www.w3.org/TR/xmlschema-2/#dateTime) allows that as well.

The pattern is used in all schemas on several occasions, e.g.
https://github.com/admin-shell-io/aas-specs/blob/ee3cdf493601f0f7f4b8c258285d324701a8c0eb/schemas/xml/AAS.xsd#L80
https://github.com/admin-shell-io/aas-specs/blob/ee3cdf493601f0f7f4b8c258285d324701a8c0eb/schemas/json/aas.json#L157
https://github.com/admin-shell-io/aas-specs/blob/ee3cdf493601f0f7f4b8c258285d324701a8c0eb/schemas/rdf/shacl-schema.ttl#L153
https://github.com/admin-shell-io/aas-specs/blob/ee3cdf493601f0f7f4b8c258285d324701a8c0eb/schemas/yaml/aas.yaml#L101

**Comment by mristin** [comment]
@jkhsjdhjs thanks for double-checking! I had another look at the specs. The time zone for the time stamps in question (*e.g.*, properties of an event) is set to UTC, hence the mandatory `Z` suffix at the end.

For example, for `BasicEventElement/lastUpdate` it says:

> Timestamp in UTC, when the last event was received (input direction) or sent (output direction).

I'll close the issue. Please re-open if we got something else wrong.

**Comment by jkhsjdhjs** [comment]
Ah, I see, thanks for the quick reply! I must have overlooked that.

**Comment by jkhsjdhjs** [comment]
@mristin Hey, I had a look again and for `lastUpdate` you're absolute right. The value is in UTC and because of that should have the `Z` suffix. But what about `minInterval` and `maxInterval`? These values represent intervals and thus it doesn't really make sense that these values are timezoned. IMO they shouldn't have any suffix, what do you think?

**Comment by mristin** [comment]
@jkhsjdhjs could you please create a separate issue so we do not spam this one?
