### ISSUE TITLE
xs:dateTime pattern doesn't allow `-00:00` and `+00:00` for UTC values

### ISSUE THREAD

**Issue by jkhsjdhjs** [admin-shell-io/aas-specs#246]
As already discussed in #244, values for `BasicEventElement/lastUpdate` are required to be specified in UTC. However, the `Z` suffix isn't the only valid way to specify UTC values, `-00:00` and `+00:00` are valid as well, see https://www.w3.org/TR/xmlschema-2/#dateTime-timezones

> The mapping so defined is one-to-one, except that '+00:00', '-00:00', and 'Z' all represent the same zero-length duration timezone, UTC; 'Z' is its canonical representation.

While Z is the canonical UTC representation, only allowing Z would be a restriction of the `dateTime` type specified in [DotAAS V3.0RC02](https://www.plattform-i40.de/IP/Redaktion/EN/Downloads/Publikation/Details_of_the_Asset_Administration_Shell_Part1_V3.pdf?__blob=publicationFile) on page 99.

**Comment by BirgitBoss** [comment]
Please see https://github.com/admin-shell-io/aas-specs/issues/245: type will be changed from dateTime to duration

Will this fix the problems you see?

**Comment by jkhsjdhjs** [comment]
Thanks for your reply! #245 adjusts the type of MinInterval and MaxInterval from `dateTime` to `duration`. However, `lastUpdate`, the property this issue is about, won't be affected by this (which is correct, `lastUpdate` represents a timestamp and should be of type `dateTime`).
The problem here is that the regular expressions specified in the schemata (referenced in #244) doesn't allow the suffix `-00:00` and `+00:00`, which is equivalent to the `Z` suffix. Yet, only the `Z` suffix is allowed.

**Comment by mristin** [comment]
@jkhsjdhjs Could you please double-check that `00:00` is equivalent to `Z`, and send me an URL so that we can reference the users and readers?

Intuitively, I agree with you, but it is not obvious. 

(Please apologize for not looking it up myself, it's busy pre-Christmas.)

**Comment by jkhsjdhjs** [comment]
@mristin Sure, it's all already contained in the issue description https://github.com/admin-shell-io/aas-specs/issues/246#issue-1448213632

**Comment by mristin** [comment]
> @mristin Sure, it's all already contained in the issue description [#246 (comment)](https://github.com/admin-shell-io/aas-specs/issues/246#issue-1448213632)

🤦‍♂️ thanks!

**Comment by mristin** [comment]
@s-heppner please take note, this is relevant for the upcoming aas-core-meta model.

**Comment by s-heppner** [comment]
As with #245, this issue does not apply to v3.0 anymore, therefore, I'll close it.
