### ISSUE TITLE
Submodel.SubmodelElements, SubmodelElementCollection and Entity.statements should be ordered

### ISSUE THREAD

**Issue by alexgordtop** [admin-shell-io/aas-specs#248]
For all cases, where a generic implementation tries to visualize multiple attributes, it is very inconvenient, when the order of the attributes differs between multiple instances of the same class (Attribute as generic synonym for SubmodelElement or Statement).

There are many examples of standardized Submodel templates with more than ten SubmodelElements. When browsing over multiple AAS with the same standardized Submodel, it would be very unhandy, if the viewed position of the same SubmodelElement is in one case at the top of the page, in another at the bottom. Or even worse, when viewing the same object multiple times, the order of elements is always shuffled - which is really annoying.

Sorting the SubmodelElements in a Viewer by alphabetical order of the idShort doesn't make sense, since it leads to technical, disfigured names like: ConnectionEndpoint, ConnectionEndpointCredName, ConnectionEndpointCredPass (to enforce, that you see first the endpoint, then username and password in the correct order (u > p)).

So please consider to specify, that the order of SubmodelElements in Submodel.SubmodelElements, SubmodelElementCollection and Entity.statements should be preserved, so that the elements can be visualized in a recurring way.

To be clear - I'm not stating, that SubmodelElements of e.g. Submodels with the same SemanticId should have always the exact index - that would foil the flexibility of Submodels and the ability to extend/adapt them. But preserving the order, once they are initialized, would be very helpful.

**Comment by alexgordtop** [comment]
@FrankSchnicke @mjacoby Issue created as discussed

**Comment by mristin** [comment]
@alexgordtop I probably lack the context -- could you please clarify which version of the meta-model you are referring to?

In the current V3RC02, the attribute `Submodel/submodelElements` is indeed an (ordered) list. This is also reflected in the schemas (*e.g.*, a JSON array, see https://github.com/admin-shell-io/aas-specs/blob/ee3cdf493601f0f7f4b8c258285d324701a8c0eb/schemas/json/aas.json#L1127).

**Comment by alexgordtop** [comment]
@mristin Ah, thanks for clarification - we couldn't figure that out from the specification document of part 1. 

Would be nice, if there would be a sentence about that in the metamodel description (table). The same applies for Entity and SubmodelElementCollection. That is, because for SubmodelElementList, it is explicitly stated, that this list is ordered - that implicates a difference to SubmodelElementCollection.

Specifically, page 78, table of SubmodelElementCollection - Explanation - It has a fixed number of submodel elements, that must keep their order, unless explicitly changed.

Page 71, table of Entity, attribute statement (missing an "s", since that are multiple ones?) - Please add "Statements must keep their order, unless explicitly changed."

Page 61, table of Submodel, attribute submodelElement (missing an "s", since that are multiple ones?) - Please add "SubmodelElements must keep their order, unless explicitly changed."

**Comment by mristin** [comment]
@BirgitBossI think this is a finding for the next version?

@alexgordtop I only help out with the schemas -- please discuss the matter with @BirgitBoss who maintains the book.

**Comment by BirgitBoss** [comment]
> @mristin Ah, thanks for clarification - we couldn't figure that out from the specification document of part 1.
> 
> Would be nice, if there would be a sentence about that in the metamodel description (table). The same applies for Entity and SubmodelElementCollection. That is, because for SubmodelElementList, it is explicitly stated, that this list is ordered - that implicates a difference to SubmodelElementCollection.
> 
> Specifically, page 78, table of SubmodelElementCollection - Explanation - It has a fixed number of submodel elements, that must keep their order, unless explicitly changed.
> 
> Page 71, table of Entity, attribute statement (missing an "s", since that are multiple ones?) - Please add "Statements must keep their order, unless explicitly changed."
> 
> Page 61, table of Submodel, attribute submodelElement (missing an "s", since that are multiple ones?) - Please add "SubmodelElements must keep their order, unless explicitly changed."

w.r.t. "s": no, all elements are described as singular in the specification, i.e. independent of the cardinality

**Comment by BirgitBoss** [comment]
w.r.t ordering I will take the requirement to the specification team

**Comment by s-heppner** [comment]
Since this issue seems to be done, I will close it. Feel free to reopen it, if this was a mistake.

**Comment by mjacoby** [comment]
Although I did not create this issue it is based on the discussion within the IDTA AAS Cloud Repository Group where I have been part of the underlying discussion.
It is still not 100% clear to me what the current situation on these issues is.

I did analyze the latest version of the specification `IDTA Number: 01001-3-0 March 2023
` available here https://industrialdigitaltwin.org/en/wp-content/uploads/sites/2/2023/06/IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf and this is what I came up with

- `SubmodelElementCollection.value` not ordered (see p. 77)
- `SubmodelElementList.value` (always) ordered, but order not always relevant (see p.78)
- `Submodel.submodelElement` no detailed information, therefore default clause (p. 139 Annex E) takes effect which says it is an unordered set
- `Entity.statement` no detailed information --> unordered set

However, this seems to be in conflict with previous answers given here, e.g. https://github.com/admin-shell-io/aas-specs/issues/248#issuecomment-1344159107 from @mristin stating that `Submodel.submodelElement` is an ordered list.

Please provide a definitive answer to these questions and for each point me to the corresponding section in the spec where this is defined.

**Comment by aorzelskiGH** [comment]
Finally I became involved into this discussion with Alexander and Michael.
I haved learned, that SubmodelElementList has an attribute "orderRelevant".
Within our 3 person discussion we concluded, that SubmodelElementList must always have an order, since the list is addressed in the API by "[index]" instead of idShort.
This needs to be discussed in the specification team.

**Comment by mjacoby** [comment]
Any updates on this? @aorzelskiGH

**Comment by empwilli** [comment]
> Within our 3 person discussion we concluded, that SubmodelElementList must always have an order, since the list is addressed in the API by "[index]" instead of idShort.
> This needs to be discussed in the specification team.

To my understanding of the examples specified in [Specification of the Asset Administration Shell - Part 1: Metamodel](https://industrialdigitaltwin.org/wp-content/uploads/2025/03/IDTA-01001-3-0-2_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf) p. 111, indexing is also valid to address elements of submodel element collections (SMCs):

> (Submodel)https://example.com/aas/1/1/1234859590, (SubmodelElementList)Documents,
> (SubmodelElementCollection)0, (MultiLanguageProperty)Title

IMHO this implies that the elements of SMCs must be interpreted as ordered.
