### ISSUE TITLE
AssetAdministrationShell_V3.0RC02.xmi can't be opened with Enterprise Architect 16.1

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/aas-specs#252]
AssetAdministrationShell_V3.0RC02.xmi can't be opened with Enterprise Architect 16.1 (current version). Same for V3.0RC02 Details of the Asset Administration Shell - Part 1.xmi

Error message:
![image](https://user-images.githubusercontent.com/118162568/213237940-e7585c25-3b90-4148-bfd3-2a9adbd35492.png)

But works for the earlier version: V3.0RC01 Details of the Asset Administration Shell - Part 1.xmi

**Comment by BirgitBoss** [comment]
I just updated xmi for the V3.0 version of Part 2:

https://github.com/admin-shell-io/aas-specs/tree/v3.0/schemas/xmi

**Comment by BirgitBoss** [comment]
Did you try to import RC02 into the same project than RC01?

**Comment by foprs** [comment]
The xmi for V3.0 version of Part 2 (AssetAdministrationSpecifications_V3.0.ea.xmi) works fine with EA. However viewing AssetAdministrationSpecifications_V3.0.norm.xmi with StarUML or Altova UModel did not work. Probably xmi as exchange format causes some problems in general.

Proposal:
Provide AssetAdministrationSpecifications_V3.0.ea.xmi as Enterprise Architect Project file. Then the EA Viewer (free) could be used. https://www.sparxsystems.eu/enterprise-architect/ea-lite-edition

**Comment by BirgitBoss** [comment]
We will consider this for the next release, thank you for the hint.

**Comment by BirgitBoss** [comment]
With V3.1 there are no .xmi files any longer but we will switch to PlantUML. 
Therefore, I will close the issue.
I
