### ISSUE TITLE
Hosted AAS v2 schema is invalid

### ISSUE THREAD

**Issue by shuebner** [admin-shell-io/aas-specs#253]
The schema hosted at `https://admin-shell-io.com/schemas/v2/aas.json` has syntax errors in it, namely 3 invalid trailing commas:
l. 78
l. 94
l. 798

This prevents validation of all submodel templates based on AAS v2, including some if not all of the [samples](https://admin-shell-io.com/samples/)

**Comment by shuebner** [comment]
The same kind of syntax error is in the ValueOnly JSON-Schema in the AAS Details Part 2.
There are two trailing commas there as well.

**Comment by sebbader-sap** [comment]
Hello @shuebner, thanks for the finding. The ValueOnly schema in the upcoming Part 2 has this fixed.

**Comment by s-heppner** [comment]
Since this appears to be fixed, I'm closing the issue. Feel free to reopen, if this was wrong.

**Comment by shuebner** [comment]
@s-heppner this is not fixed. The hosted AAS is still invalid .

**Comment by sebbader-sap** [comment]
Note: https://admin-shell-io.com/ is, as far as I know, not controlled by the community of this GitHub repository. The file at https://github.com/admin-shell-io/aas-specs/blob/master/schemas/json/aas.json and the ones published in the document series "Specification of the Asset Administration Shell" are the only ones we can fix.
Anyone knows who controls the server behind https://admin-shell-io.com/?

**Comment by sebbader-sap** [comment]
As long as this is not clarified, I have no idea how we can fix it from here and therefore wouldn't open the issue.

**Comment by shuebner** [comment]
Too bad. Your decision then :-)
