### ISSUE TITLE
json in xml//examples/generated/Environment folder

### ISSUE THREAD

**Issue by arnoweiss** [admin-shell-io/aas-specs#256]
There seems to be some faulty example data generation. The data in this folder is json instead of xml. 

https://github.com/admin-shell-io/aas-specs/tree/ee3cdf493601f0f7f4b8c258285d324701a8c0eb/schemas/xml/examples/generated/Environment

**Comment by mristin** [comment]
@arnoweiss thanks! It slipped probably during the updates. Please give me some time as I am quite busy with V3.

Just in case if you need the data immediately, it is available here: https://github.com/aas-core-works/aas-core3.0rc02-testgen/tree/main/test_data/Xml

The particular example you addressed is here: https://github.com/aas-core-works/aas-core3.0rc02-testgen/tree/main/test_data/Xml/SelfContained/Expected/environment

If you have time, it would be great if you could simply make a pull request and copy/paste the data from https://github.com/aas-core-works/aas-core3.0rc02-testgen/tree/main/test_data/Xml/SelfContained/Expected/environment.

**Comment by BirgitBoss** [comment]
I think this is fixed by now and this issue can be closed. Please reopen if still valid. Thank you for reporting!
