### ISSUE TITLE
IEC 61360 DataType Inconsistency INTEGER and INTEGER_MEASURE

### ISSUE THREAD

**Issue by br-iosb** [admin-shell-io/aas-specs#26]
Hello,

it looks like the string enumeration in IEC61360.xsd contains "INTEGER" and not "INTEGER_MEASURE", while for JSON and RDF "INTEGER_MEASURE" and not "INTEGER" are listed.

I don't know about that IEC 61630 datatype but i think the string representation should be consistent regardless of the used format.

**XML**

	<simpleType name="dataTypeIEC61360_t">
		<restriction base="string">
			<enumeration value="" />
			<enumeration value="BOOLEAN" />
			<enumeration value="DATE" />
			<enumeration value="RATIONAL" />
			<enumeration value="RATIONAL_MEASURE" />
			<enumeration value="REAL_COUNT" />
			<enumeration value="REAL_CURRENCY" />
			<enumeration value="REAL_MEASURE" />
			<enumeration value="STRING" />
			<enumeration value="STRING_TRANSLATABLE" />
			<enumeration value="TIME" />
			<enumeration value="TIMESTAMP" />
			<enumeration value="URL" />
			<enumeration value="INTEGER" />
			<enumeration value="INTEGER_COUNT" />
			<enumeration value="INTEGER_CURRENCY" />
		</restriction>
	</simpleType>
	
**RDF**

	    owl:oneOf (
        iec61360:DATE
        iec61360:STRING
        iec61360:STRING_TRANSLATABLE
        iec61360:INTEGER_MEASURE
        iec61360:INTEGER_COUNT
        iec61360:INTEGER_CURRENCY
        iec61360:REAL_MEASURE
        iec61360:REAL_COUNT
        iec61360:REAL_CURRENCY
        iec61360:BOOLEAN
        iec61360:URL
        iec61360:RATIONAL
        iec61360:RATIONAL_MEASURE
        iec61360:TIME
        iec61360:TIMESTAMP
    ) ;
	
**JSON**

	             "enum": [
                "DATE",
                "STRING",
                "STRING_TRANSLATABLE",
                "REAL_MEASURE",
                "REAL_COUNT",
                "REAL_CURRENCY",
                "BOOLEAN",
                "URL",
                "RATIONAL",
                "RATIONAL_MEASURE",
                "TIME",
                "TIMESTAMP",
                "INTEGER_COUNT",
                "INTEGER_MEASURE",
                "INTEGER_CURRENCY"
              ]

**Comment by JoergWende** [comment]
need to check with the JSON / RDF guys ...

**Comment by BirgitBoss** [comment]
The AAS spec say INTEGER_MEASURE, so this seems to be a bug in xsd.

**Comment by JoergWende** [comment]
ok ... my turn
