### ISSUE TITLE
Remove non-V3 examples

### ISSUE THREAD

**Issue by arnoweiss** [admin-shell-io/aas-specs#260]
In the examples, there are still many files complying to V3RC02. [Here](https://github.com/admin-shell-io/aas-specs/tree/master/schemas/xml/examples/generated/assetAdministrationShell), this led to the situation that `maximal.xml` and `complete.xml` both remain on github despite `complete.xml` being out of date. Seems like an accidental git-issue.

**Comment by arnoweiss** [comment]
This issue persists beyond XML, see [here](https://github.com/admin-shell-io/aas-specs/tree/master/schemas/json/examples/generated/AssetAdministrationShell
) where you still have a complete.json and a maximal.json. I haven't checked for rdf and yml. Please reopen.

**Comment by mristin** [comment]
@s-heppner could you please have a look? Probably best if you deleted *all* the files and re-copied them?

**Comment by s-heppner** [comment]
Yes, I'll double check it.

**Comment by s-heppner** [comment]
I have updated the examples of RDF and JSON in #276. Sorry for not directly checking all examples. 

In order to avoid these kind of human-made errors, I propose we think about a way to automate the aggregation process: #267 
Ideas are welcome.
