### ISSUE TITLE
Update xsd to V3

### ISSUE THREAD

**Issue by arnoweiss** [admin-shell-io/aas-specs#261]
In the xsd for the AAS meta-model-schema, there is a very important line missing. If it's not there, AAS-environments and their components (everything) will not be recongnized as such. It should be here:
https://github.com/admin-shell-io/aas-specs/blob/6f7d5b1e386d950cbd02c477d80065fb2e95fa99/schemas/xml/AAS.xsd#L1341

In the test-data of the testgen-repository, [it is correct](https://github.com/aas-core-works/aas-core3.0-testgen/blob/403a0a7cca4a787f642b226bc940ae2d2b319dad/test_data/schema.xsd#L1342).

**Comment by arnoweiss** [comment]
@s-heppner - is there any update on this? I suspect since it is correct in the generator, this will most likely be a sync-problem. The XSD as it is currently in the repo is not usable.

**Comment by s-heppner** [comment]
That sounds weird indeed. I'll have a look at it.

**Comment by arnoweiss** [comment]
looks good now - thanks to @s-heppner and @sebbader-sap
