### ISSUE TITLE
How to differentiate Submodels via discriminator (modelType)?

### ISSUE THREAD

**Issue by hmrc87** [admin-shell-io/aas-specs#262]
SubmodelElements possess unique discriminators, such as 'File'. 

However, for standardized Submodels like DigitalNameplate, will there be custom discriminators to improve serialization and deserialization processes?

**Comment by arnoweiss** [comment]
I highly doubt that. The only way to tell if a Submodel Instance signalizes conformance to a standardized Submodel Template (like DigitalNameplate) is equivalent semanticIds. Whether it actually *is* conformant (including all mandatory elements as standardized) currently can't be validated automatically. There's an IDTA group working on this.

**Comment by hmrc87** [comment]
Thanks for the quick answer, Arno. We will ask around in the next IDTA Meetings and try to find out who is working on this topic
