### ISSUE TITLE
BUG - Workflow for bugs and features seem not to work

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#271]
When creating a new issue no templates for bugs and features are raised although available:
https://github.com/admin-shell-io/aas-specs/tree/master/.github/workflows/ISSUE_TEMPLATE

**Comment by sebbader-sap** [comment]
We probably need to move the files from .github/workflows/ISSUE_TEMPLATE to .github/ISSUE_TEMPLATE, at least according to https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by BirgitBoss** [comment]
files moved from workflows to ISSUE_TEMPLATE
