### ISSUE TITLE
Outdated examples or outdated README

### ISSUE THREAD

**Issue by jh-isw** [admin-shell-io/aas-specs#279]
https://github.com/admin-shell-io/aas-specs/blob/21e68502e367b72fd82cfa29488a686cbd3892a5/schemas/json/examples/README.md?plain=1#L3

According to this line, the examples are from V3.0RC02
though the latest commit message on the examples implies V3.0

**Comment by mristin** [comment]
Thanks, @jh-isw ! I'll try to fix it tomorrow.

**Comment by jh-isw** [comment]
You're welcome :)
