### ISSUE TITLE
Inconsistency in chapter 4.3 version 3.0RC1

### ISSUE THREAD

**Issue by mmarseu** [admin-shell-io/aas-specs#28]
In the latest release candidate, chapter 4.3 still references the attribute **Asset/billOfMaterial** which has been replaced in that version by **AssetInformation/billOfMaterial**.
The diagram in the same chapter doesn't mention **AssetInformation** at all and still suggests the bill of material would be part of the asset.

**Comment by BirgitBoss** [comment]
This will be fixed in the next release of the specification.

**Comment by BirgitBoss** [comment]
I close the issue since the change was already done.
