### ISSUE TITLE
Missing DataTypeDefXsd in SHACL Shape

### ISSUE THREAD

**Issue by mhrimaz** [admin-shell-io/aas-specs#281]
From my impression SHACL shape should validate the existing examples such [this one](https://github.com/aas-core-works/aas-core3.0-testgen/blob/main/test_data/Rdf/ContainedInEnvironment/Expected/Property/OverValueExamples/Decimal/decimal.ttl) which is equivalent to [this JSON](https://github.com/aas-core-works/aas-core3.0-testgen/blob/main/test_data/Json/ContainedInEnvironment/Expected/Property/OverValueExamples/Decimal/decimal.json).
However if you give your shape and data to existing tools such as [SHACL Playground](https://shacl.org/playground/), you would get validation error:

![image](https://github.com/admin-shell-io/aas-specs/assets/17963017/cb09b11c-87bc-4ef3-bf9e-9c7f38694557)

In [xml schema](https://github.com/aas-core-works/aas-core3.0-testgen/blob/main/test_data/schema.xsd#L967) `DataTypeDefXsd` and also json schema it is defined. however, it seems it is missing for shacl shape. 

So I think it we should either add definition for `DataTypeDefXsd` or simply replace it with `sh:in (xs:string xs:decimal other possible values)` ;

Please let me know I am in a wrong direction @sebbader

**Comment by sebbader-sap** [comment]
@mhrimaz thanks for the comment.

You need to tell the validator not only about the shapes graph but also the rest of the AAS ontology. You can do this by adding the content of the file "rdf-ontology.ttl" to the *Data Graph*. 

Additionally, this playground is not able to support SPARQL shapes so you also need to get rid of these from the shapes graph first. Any full-fledged shacl validator can work with them, of course.

With these adjustment, the example is validated without any errors. Therefore, I am closing the ticket. Feel free to reopen it if it still doesn't work for you.
