### ISSUE TITLE
Remove obsolete complete.json file

### ISSUE THREAD

**Issue by FrankSchnicke** [admin-shell-io/aas-specs#282]
In the JSON examples, there are minimal.json, maximal.json, complete.json files, e.g., [here](https://github.com/admin-shell-io/aas-specs/tree/master/schemas/json/examples/generated/Extension). However, the complete.json seems to be outdated and is superseded by maximal.json. Thus, the file should be removed for all examples.

**Comment by mristin** [comment]
Fixed by #276.

Thanks for letting us know, @FrankSchnicke! The PR #276 was still pending review. We merged it now.


@FrankSchnicke please re-open if #276 did not fix the issue.
