### ISSUE TITLE
AAS.xsd imposes restrictions to AdministrativeInformation version and revision that doesn't exist in JSON schema

### ISSUE THREAD

**Issue by twebermartins** [admin-shell-io/aas-specs#288]
Please refer to Issue in Eclipse AAS4J (https://github.com/eclipse-aas4j/aas4j/issues/148). 

It seems that there is a mismatch regarding constraints for AASX / XML and JSON.

**Comment by mristin** [comment]
@twebermartins thanks for reporting the issue!

@sebbader-sap It might be a bug in the JSON schema generator, but I am not sure. I also remember vaguely that we had already discussed the cases of constrained strings with multiple patterns, but can not recall the details right now.

Please apologize the delay; it's holiday season. We should sort this out mid-August 2023.

**Comment by sebbader-sap** [comment]
No intention to point to anyone, and also no need to work during anyone's holidays, please! Just had the feeling that it might happened on purpose, and in that case I was curious about the reasoning behind it.
