### ISSUE TITLE
Is there a consistent approach to mapping a classification of assets in the AAS?

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/aas-specs#292]
In the "Generic Frame for Technical Data for Industrial Equipment in Manufacturing" (IDTA 02003), a guideline for the creation of submodel templates for technical data of assets, for example, the SubmodelElementCollection ProductClassifications is described. Would not be a classification of assets also in AssetInformation usefull for every kind of Asset?

**Comment by BirgitBoss** [comment]
If the answer does not satisfy your requirements please feel free to reopen it.

**Comment by BirgitBoss** [comment]
This was discussed but rejected or postponed in previous releases but we might discuss it again.

**Comment by BirgitBoss** [comment]
Discussion 2023-11-23 Workstream AAS

A similar request was rejected in the past

Alternatives:

1. use assetType not only for asset IDs but also for classification
2. add semanticId to AssetInformation (inherit from HasSemantics)
3. no change, assetClassification should be part of technical data or other submodel
4. add new attribute "assetClassification" with type Identifier and Cardinality 0..1
5. add new attribute "assetClassification" with type Identifier and Cardinality 0..*
6. generic key-value pairs (additional to specificAssetIds)

performance/simpllicity of API versus rich metamodel. Discovery topic, will be further discussed in Discovery TF
