### ISSUE TITLE
Clarification Request Regarding Language Tags Constraints

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/aas-specs#293]
In Specification Part 1, there is information regarding language tags as follows:
"RDF requires IETF BCP 47[20] language tags. Simple two-letter language tags for locales like "de" conformant to ISO 639-1 are allowed, as well as language tags plus extension like "de-DE" for country code, dialect, etc. like in "en-US" for English (United States) or "en-GB" for English (United Kingdom). IETF language tags are referencing ISO 639, ISO 3166 and ISO 15924."

Could you please provide more specific details about these requirements? Have I understood correctly that language tags must adhere to the IETF BCP 47 standard with certain restrictions? Are these restrictions as follows:
- The `langtag` must correspond to ISO 639-1.
- Only two-letter language tags are allowed + optional extensions `script` and `region`, which must comply to ISO 15924 and ISO 3166. So, are tags like "de-Latn" or "de-Latn-DE" also allowed?

If this is the case, could you please formalize an AASd-Constraint that outlines the limitations of language tags in AAS?

**Comment by BirgitBoss** [comment]
renaming of constraints in Part 3a was done in V3.0.2

**Comment by BirgitBoss** [comment]
new issue https://github.com/admin-shell-io/aas-specs-iec61360/issues/43 for Part 3a since AASc-002 is part of Part 3a. This issue can be closed since no impact on Part 1
