### ISSUE TITLE
Inconsistency in the cardinality of DataSpecification in EmbeddedDataSpecification

### ISSUE THREAD

**Issue by juileetikekar** [admin-shell-io/aas-specs#296]
As per the "Specification of Asset Administration Shell Part1 - Metamodel", section 7.2.5, figure 58 "Realization of Embedded Data Specification", the DataSpecification is an optional parameter in EmbeddedDataSpecification. However, in the [SwaggerHub definitions ](https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/EmbeddedDataSpecification)or in ["aas-core-works" HTML rendered pages](https://aas-core-works.github.io/aas-core-meta/v3/EmbeddedDataSpecification.html), the DataSpecification is a mandatory parameter. The generated "aas-core-sdk (c#)" also treats it as a mandatory parameter. So, the question here is, if the DataSpecification should be treated as optional or mandatory parameter in EmbeddedDataSpecification?  

Figure 58 from "Specification of Asset Administration Shell Part1 - Metamodel"
![MicrosoftTeams-image (2)](https://github.com/admin-shell-io/aas-specs/assets/99317579/5644ce86-f78c-4aaf-b13b-ac130d3a1142)

**Comment by BirgitBoss** [comment]
Thank you so much for this finding. Yes, this is an inconsistency that needs to be fixed.

**Comment by sebbader-sap** [comment]
> I recommend to make the EmbeddedDataSpecification/dataSpecification mandatory.

This means that the JSON Schema will be changed (and therefore also https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1), correct?

**Comment by BirgitBoss** [comment]
no, schema will not be changed, only the documentation

**Comment by BirgitBoss** [comment]
fixed

**Comment by BirgitBoss** [comment]
solved in IDTA-01001-3-0-1: https://industrialdigitaltwin.org/wp-content/uploads/2024/06/IDTA-01001-3-0-1_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf
