### ISSUE TITLE
[BUG] Qualifiable should not have ModelType

### ISSUE THREAD

**Issue by mhrimaz** [admin-shell-io/aas-specs#300]
# What happens?
In api specification `Qualifiable` has `ModelType` which is wrong.

![image](https://github.com/admin-shell-io/aas-specs-api/assets/17963017/6221cc2c-b941-4929-85a8-91902da83f18)

...

# Why is this wrong?

We don't have any corresponding `ModelType` for `Qualifiable`. Neither in metamodel nor in current api specification.

![image](https://github.com/admin-shell-io/aas-specs-api/assets/17963017/f65581f7-3d7b-4e9d-ad07-31bdc6b568fa)

# How should it be fixed?

I would suggest to add `Qualifier` in the `ModelType` enum. And then add `ModelType` to `Qualifier` instead of `Qualifiable`. This would introduce less backward compatibility issue.
Otherwise, we need to remove it from api specification.

...

- [x] I have signed the required Developer Certificate of Origin ([DCO](https://developercertificate.org)) already.

**Comment by BirgitBoss** [comment]
Issue added to aas-core-codegen: https://github.com/aas-core-works/aas-core-codegen/issues/423

**Comment by BirgitBoss** [comment]
closed, see https://github.com/aas-core-works/aas-core-codegen/issues/423 for resolution: modelType is a discriminator for JSON serialization.
If your issue is not solved please feel free to reopen again.
