### ISSUE TITLE
Missing Modeling Element for Cardinality

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/aas-specs#303]
The cardinality between model elements is an inherent information. But there is no model element in the meta model defined to model the cardinality.

The only more or less "hard" reference to use qualifier types is here: https://industrialdigitaltwin.org/wp-content/uploads/2022/12/I40-IDTA-WS-Process-How-to-write-a-SMT-FINAL-.pdf

Is there a reason why cardinality is not adressed directly to be modelled in an AAS, e.g., as attribute of a Submodel Element?

**Comment by BirgitBoss** [comment]
submodel instances do not have cardinalities, submodel templates guide the creation of submodel instances using the semantics as specified in semanticId as well as template and concept qualifier.
