### ISSUE TITLE
Feedback for other related documents / specifications

### ISSUE THREAD

**Issue by mmarseu** [admin-shell-io/aas-specs#32]
This github already serves well for the general public to get in touch with the authors of the AAS specification with feedback or questions. I myself have made use of this channel a few times already.

Is there a similar way to discuss other outputs of the specification working group? For instance, I have a question regarding the submodel template for digital nameplates but the document doesn't give any indication where to go for help.
Is this project the right place to ask my questions?

**Comment by sebbader** [comment]
Hi @mmarseu ! That's a good point. In general, this repo is used to track very detailed change requests or bugs in the model/serializations. Let me write you an email and make contact with the authors of the Digital Nameplate Template.

**Comment by sebbader** [comment]
There is no public forum or something like an official communication channel for the community (at least I don't know any). One could however think about something, maybe in the context of the IDTA?

**Comment by BirgitBoss** [comment]
In the moment https://github.com/admin-shell-io/questions-and-answers is best suited for questions. But you are right, we should think about setting up a communication channel for the community.

**Comment by mristin** [comment]
Closing as not related to AAS specs.
