### ISSUE TITLE
[BUG] In the Specification (01001-3-0) there are inconsistencies whether a semanticId is recommended or mandatory

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/aas-specs#332]
**Describe the bug**
In the Specification (01001-3-0) there are inconsistencies whether a semanticId is recommended or mandatory.

**Where**
Page 44 is written:
"Every submodel element needs a semantic definition (semanticId in HasSemantics) to have a well-defined
meaning. The submodel element might either refer directly to a corresponding semantic definition provided
by an external reference (e.g. to an ECLASS or IEC CDD property definition) or it may indirectly reference a
concept description (ConceptDescription). See Clause 4.4.1 for matching strategies, and Clause 5.3.2.6 for
details."

Page 30/31 (Table 2) is written "recommended"

Cardinality in the class diagram of HasSemantics is 0..1

**Comment by arnoweiss** [comment]
I always go back to the schemas if I want to get an authoritative view on such structural issues. They reinforce the class diagrams - semanticIds are always optional. 

Not sure if I read the quote on p.44 the same way as you. The first sentence is key. My interpretation is:
- semanticIds give well-defined meaning to submodel elements.
- Not all submodel elements must have well-defined meaning.
