### ISSUE TITLE
Matching Strategy: Outdated equivalence of ModelReference[Submodel] and GlobalReference with same key

### ISSUE THREAD

**Issue by s-heppner** [admin-shell-io/aas-specs#350]
[Page 36 of the v3.0 Part 1 specification](https://industrialdigitaltwin.org/wp-content/uploads/2023/06/IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf#Page=36) mentions an equivalence relationship: 

> (Submodel)https://example.com/aas/1/1/1234859590
> is identical to
> (GlobalReference)https://example.com/aas/1/1/1234859590

At first glance, this is logical in the sense that both References refer to the same (Submodel) object. 

However, there is a difference between `ModelReference` and `GlobalReference`, as `ModelReference`s are resolvable in implementations of the AAS (since it references another AAS object), whereas `GlobalReference` does not necessarily refer to other AAS objects. 
Furthermore, in the case of `AssetAdministrationShell/submodel`, the spec requires a `ModelReference[Submodel]` anyway, making this equivalence relationship confusing and outdated, as far as I can see. 

This issue came up due to an AAS wrongly modelled under this assumption in [basyx-python-sdk#231](https://github.com/eclipse-basyx/basyx-python-sdk/issues/231)

**Comment by g1zzm0** [comment]
Is it possible to check only the Identifiers?

**Comment by BirgitBoss** [comment]
You are right. In "in the case of AssetAdministrationShell/submodel, the spec requires a ModelReference[Submodel] " in this case it would be a bug to use an external reference. The documentation needs to be clearer on the use cases these "equivalence"-relationship matches hold. It does not mean you can just substitute them in every context.

**Comment by BirgitBoss** [comment]
@joergneidig: can you please review: https://rwth-iat.github.io/aas-specs-antora/IDTA-01001/snapshot/IDTA-01001_General.html#_matching_algorithm_for_references

**Comment by JoergNeidig** [comment]
> @JoergNeidig: can you please review: https://rwth-iat.github.io/aas-specs-antora/IDTA-01001/snapshot/IDTA-01001_General.html#_matching_algorithm_for_references

The new/changed notes add to the clarity of the matching. I agree on making these changes.

**Comment by BirgitBoss** [comment]
Worksteam AAS Specs 2024-06-13
accepted to add these clarifying notes
