### ISSUE TITLE
Individual versioning of metamodel element IDs

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#366]
**Is your feature request related to a problem? Please describe.**
Up to V3.0 all elements got a new version, e.g. `https://admin-shell.io/aas/3/1/AssetAdministrationShell` even if there was no change.

If there are no changes then the version should not be increased. Inherited class changes need to be considered in the version. So if the class A that is inherited by class B is changed then also the version of class B is increased.
Same for type changes. If a type A is changed and used as type in one of the attributes in class B then the version of class B needs to be increased as well.
The third case is the change of constraints: if a constraint has an impact on the allowed values of a class B the the version of class B needs to be increased.

Same for API operations in Part 2

**Comment by BirgitBoss** [comment]
Decision Work Stream AAS Specifications 2023-12-14:
individual versioning

**Comment by mristin** [comment]
@BirgitBoss the aas-core supports only one namespace per meta-model, so this can not be implemented using aas-core.

**Comment by BirgitBoss** [comment]
@mristin yes, I assumed so. However, what aas-core defined is not the namespace for the elements but just the version of the specification as a whole the elements are part of.

So there would be (example only) the need to map

`https://admin-shell.io/aas/3/0/AssetKind` 
to
`https://aas-core-works.github.io/aas-core-meta/v3_1/AssetKind.html`
if the version of AssetKind remains the same in V3.1 of IDTA-01001.

This is more work than before, this is true. I discussed it with responsible from https://github.com/admin-shell-io/id.

**Comment by mristin** [comment]
@BirgitBoss Please note that aas-core can not handle different namespaces in XML, JSON, RDF, generated SDKs *etc.*

**Comment by BirgitBoss** [comment]
2024-03-07 Workstream AAS
Discussion:
Distinguish between:
- Generating Schema
- Redirect semantic Identifier
- Documentation

![image](https://github.com/admin-shell-io/aas-specs/assets/59824205/8ad3b864-64cd-4b0f-802c-ed051558b109)


Alternatives discussed:
A) (revise decision) increase all versions (of classes and operations and profiles in all parts) to V3.1 
B)  stay with individual versioning, no generation of rdf possible any longer, xml schema namespace not consistent with versioning in documentation

**Decision:**
- For now we stay with A) like we did in previous versions
- We may rediscuss it 4.x
- documentation will contain semanticId for all classes and attributes, operation, profiles etc. to make semanticId transparent

**Comment by mhrimaz** [comment]
@BirgitBoss not sure if I have to open a new issue or just write my comment here. 

This is an rdf data:

```turtle
@prefix aas: <https://admin-shell.io/aas/3/0/> .
@prefix xs: <http://www.w3.org/2001/XMLSchema#> .

<something_142922d6> a aas:AssetAdministrationShell ;
    <https://admin-shell.io/aas/3/0/Identifiable/id> "something_142922d6"^^xs:string ;
    <https://admin-shell.io/aas/3/0/AssetAdministrationShell/assetInformation> [
        a aas:AssetInformation ;
        <https://admin-shell.io/aas/3/0/AssetInformation/assetKind> <https://admin-shell.io/aas/3/0/AssetKind/NotApplicable> ;
        <https://admin-shell.io/aas/3/0/AssetInformation/globalAssetId> "something_eea66fa1"^^xs:string ;
    ] ;
.
```

I have a SPARQL query to filter based on assetKind:
```sparql
prefix aas: <https://admin-shell.io/aas/3/0/> 

SELECT *
{
    ?aas a aas:AssetAdministrationShell;
         <https://admin-shell.io/aas/3/0/AssetAdministrationShell/assetInformation> ?asset_info.
    ?asset_info <https://admin-shell.io/aas/3/0/AssetInformation/assetKind> ?asset_kind .
    FILTER(?asset_kind = <https://admin-shell.io/aas/3/0/AssetKind/NotApplicable>)
}
```

So now the new minor-version comes out, which suppose to be a non-breaking change. In fact, the only change here is adding new assetKind, and constraint relaxation. So I expect my system should be fine.

But the new data will be like the following:
```turtle
@prefix aas: <https://admin-shell.io/aas/3/1/> .
@prefix xs: <http://www.w3.org/2001/XMLSchema#> .

<something_142922d6> a aas:AssetAdministrationShell ;
    <https://admin-shell.io/aas/3/1/Identifiable/id> "something_142922d6"^^xs:string ;
    <https://admin-shell.io/aas/3/1/AssetAdministrationShell/assetInformation> [
        a aas:AssetInformation ;
        <https://admin-shell.io/aas/3/1/AssetInformation/assetKind> <https://admin-shell.io/aas/3/1/AssetKind/NotApplicable> ;
        <https://admin-shell.io/aas/3/1/AssetInformation/globalAssetId> "something_eea66fa1"^^xs:string ;
    ] ;
.
```
So with the new version of the same data, my queries won't work anymore. 

So, this is not inherently something impossible to handle. But it makes things harder. So now to make my SPARQL query generic, now I need to rely on STRING manipulations a lot more, which reduce performance and readability.
```sparql
SELECT *
{
    ?aas a ?asset_type;
         ?asset_info_link ?asset_info.
    FILTER(STRENDS(STR(?asset_type),"AssetAdministrationShell"))
    FILTER(STRENDS(STR(?asset_info_link),"AssetAdministrationShell/assetInformation"))
    ?asset_info ?asset_kind_link ?asset_kind .
    FILTER(STRENDS(STR(?asset_kind_link ),"AssetInformation/assetKind"))
    FILTER(STRENDS(STR(?asset_kind),"AssetKind/NotApplicable"))
}
```

To give you a better understanding, this is same as putting the version info in the keys in the JSON serialization.
So if you want to have instead of the following json:
```json
{
  "assetAdministrationShells": [
    {
      "assetInformation": {
        "assetKind": "NotApplicable",
        "globalAssetId": "something_eea66fa1"
      },
      "id": "something_142922d6",
      "modelType": "AssetAdministrationShell"
    }
  ]
}
```
have 
```json
{
  "assetAdministrationShells-v3-0": [
    {
      "assetInformation-v3-0": {
        "assetKind-v3-0": "NotApplicable",
        "globalAssetId-v3-0": "something_eea66fa1"
      },
      "id-v3-0": "something_142922d6",
      "modelType-v3-0": "AssetAdministrationShell"
    }
  ]
}
```
then this is fine for me!

Regardless, I understand individual versioning has other side effects.
One possible way is to not include minor version increment in the versioning (atleast at the serialization level).
```turtle
@prefix aas: <https://admin-shell.io/aas/3/> .
@prefix xs: <http://www.w3.org/2001/XMLSchema#> .

<something_142922d6> a aas:AssetAdministrationShell ;
    <https://admin-shell.io/aas/3/Identifiable/id> "something_142922d6"^^xs:string ;
    <https://admin-shell.io/aas/3/AssetAdministrationShell/assetInformation> [
        a aas:AssetInformation ;
        <https://admin-shell.io/aas/3/AssetInformation/assetKind> <https://admin-shell.io/aas/3/1/AssetKind/NotApplicable> ;
        <https://admin-shell.io/aas/3/AssetInformation/globalAssetId> "something_eea66fa1"^^xs:string ;
    ] ;
.
```
Another possible way is to not increment the minor version at all. keep it always zero :)

BTW, in any case the current RDF (Ontology) and SHACL are not wrong and unusable!

ps: you can try the queries on https://atomgraph.github.io/SPARQL-Playground/

**Comment by BirgitBoss** [comment]
Thanks for the examples and making us aware of the consequences for rdf.

For the API we recommend to only use the major version.
