### ISSUE TITLE
[BUG] The spelling of ID-Short-Path should be uniform

### ISSUE THREAD

**Issue by g1zzm0** [admin-shell-io/aas-specs#385]
**Describe the bug**
The spelling of ID-Short-Path should be uniform. In the PDF and ASCII Doc are several spellings of IdShort-Path, IDShortPath, etc.

**Where**
PDF Spec and ASCII Doc

**Screenshots**
![image](https://github.com/admin-shell-io/aas-specs/assets/1814815/241f43eb-4d60-4ed7-9142-e08b1c247921)
![image](https://github.com/admin-shell-io/aas-specs/assets/1814815/9a318b7b-039a-47dc-ae8b-84da5f18a4ca)

**Additional context**
id-short-path could not be found with the Antora search feature.

**Comment by BirgitBoss** [comment]
same for IRDI path and IRDI-Path: use IRDI-Path

**Comment by zrgt** [comment]
Fixed in #469
