### ISSUE TITLE
Definition of Cardinality seems to be wrong (01001-3-0, p.  134)

### ISSUE THREAD

**Issue by foprs** [admin-shell-io/aas-specs#388]
**Describe the bug**

The definition for "0..*" or "0..3" seems to be wrong. Cardinality "1" is missing.

*Card. is the cardinality (or multiplicity) defining the lower and upper bound of the number of
instances of the member element. "*" denotes an arbitrary infinite number of elements of the
corresponding Type. "0..1" means optional. "0..*" or "0..3" etc. means that the list may be either not
available (null object) or empty.*

**Where**
01001-3-0, p.  134

**Comment by BirgitBoss** [comment]
You are right, this should be added.
