### ISSUE TITLE
Proposal for MultiLanguageFile Support

### ISSUE THREAD

**Issue by alaettindogan** [admin-shell-io/aas-specs#392]
During the recent IDTA General Assembly, I addressed an issue that emerged during our development work: the lack of support for MultiLanguageFiles. While we have Property and MultiLanguageProperty, there's no analogous feature for files. This gap complicates the implementation of multilanguage support without having to model each language as a separate element collection. Extending multilingual capabilities to files (and potentially other elements) could significantly enhance our flexibility. I'd like to bring this matter up for discussion.

**Comment by BirgitBoss** [comment]
It would need to support a set of languages since some documents contain text in several languages.

**Comment by BirgitBoss** [comment]
2024-10-16 TF AAS Metamodel
- language information on files/documentation is contained as properties in the [Submodel template "documentation"](https://industrialdigitaltwin.org/wp-content/uploads/2023/03/IDTA-02004-1-2_Submodel_Handover-Documentation.pdf)
- if we start adding language as meta information to file there probably will be other information as well that others want to add.
==> we recommend to not extend the metamodel
