### ISSUE TITLE
XSD datatype version mismatch

### ISSUE THREAD

**Issue by g1zzm0** [admin-shell-io/aas-specs#395]
**Describe the bug**
The specified data types for the AAS of XSD Datatype Version 1.0 and the RDF data types (e.g. rdf:Langstring) of XSD Datatype Version 1.1 do not match.
RDF uses the referenced RDF 1.1 and therefore the XSD Datatypes version 1.1.
The datatypes defined for RDF 1.1 is https://www.w3.org/TR/rdf11-concepts/#xsd-datatypes and references the XSD Version 1.1 https://www.w3.org/TR/xmlschema11-2/#built-in-primitive-datatypes instead of the AAS Datatypes uses XSD Version 1.0 https://www.w3.org/TR/xmlschema-2/#built-in-primitive-datatypes

**Where**
Specification of Primitive and Simple Data Types in Version 3.0, 3.0.1 and 3.1

**Screenshots**
![image](https://github.com/admin-shell-io/aas-specs/assets/1814815/58540633-0f46-4ffb-8f99-a18caa1f847c)

**Additional context**
No matter in which version RDF uses the XSD data types version 1.1

**Comment by BirgitBoss** [comment]
So far the only datatype Part 1 is using from RDF is langString, all other types from RDF are not used in the metamodel. 

So from metamodel point of view we need to have a look at string and AASd-130. If the string definition in XML Schema 1.0 and 1.1 differs then we need to decide whether MultiLanguageProperties have a different string constraint than "normal" Properties with type xs:string.

The impact on the serialization formats, especially RDF is not clear to me.

**Comment by sebbader-sap** [comment]
1. RDF 1.1 references XML Schema Part 2 - Datatypes Version 1.1, indeed.
2. However, this has no effect on the AAS RDF serialisation, and is completely unrelated to the decision that AAS relies on XML Schema version 1.0. The AAS RDF serialisation only uses the native RDF datatypes xs:string, xs:boolean, and xs:base64byte, which are already in XML Schema Part 2 - Datatypes Version 1.0

So I think we face a pretty complex situation but have a pretty easy solution: Current state is fine, no changes needed :-).

**Comment by BirgitBoss** [comment]
2024-06-13 Workstream AAS Specs
accepted, we stay with XML Schema 1.0 data types although RDF is using XML Schema 1.1 data types.

**Comment by BirgitBoss** [comment]
solved in IDTA-01001-3-0-1: https://industrialdigitaltwin.org/wp-content/uploads/2024/06/IDTA-01001-3-0-1_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf
