### ISSUE TITLE
Serialization of operations wrong (XML Schema)?

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#40]
Please check serialization of operations:
see
https://github.com/admin-shell-io/aasx-package-explorer/issues/387#issuecomment-883529947

It should be
```
<aas:inoutputVariables>
   <aas:operationVariable>... </aas:operationVariable>
   <aas: operationVariable>... </aas:operationVariable>
<aas:inoutputVariables>
```
according to specification, doesn't it?

**Comment by mristin** [comment]
Closing the issue due to inactivity. @BirgitBoss please re-open the issue with concrete examples if it hasn't been fixed in the draft for V3RC02.
