### ISSUE TITLE
Cardinality > 1, distinguish between Map / Array

### ISSUE THREAD

**Issue by alexgordtop** [admin-shell-io/aas-specs#411]
The model should distinguish for attributes with cardinality > 1, it it is a kind of array/list or a kind of object/map.

This is relevant for Value-Only serialization only. For Normal it is always an array.

**Comment by BirgitBoss** [comment]
In Part 2 for interfaces 

![image](https://github.com/admin-shell-io/aas-specs/assets/59824205/83d518e2-4c76-4c98-a5cf-566731e6c389)

Mandatory and Cardinality are distinguished. So there might be an optional element but the cardinality is 1. No Null object allowed in this case.

Similar we can add an additional column to the class definitions. For all cases with 0..1, 0..* etc. we need to define whether empty lists or NULL objects are allowed. To be backward compatible to the schema implementations we would have in the moment:

- mandatory: false
- Cardinality: 1 or 1..* 
etc.

**Comment by s-heppner** [comment]
If I get this correctly, you want to specify in the model how a given attribute with cardinality > 1 should be implemented? (As a list or an array?)

That is nothing a technology-neutral model should specify in my opinion. What if there was an AAS implementation in a programming language that handles multivalued attributes differently and does not offer one or the other? 
If you want to specify this, it should be in the return value of the API call, imo. 

Please correct me, if I didn't get the problem right.

**Comment by BirgitBoss** [comment]
2024-11-27 TF AAS Spec Metamodel
SubmodelElementList are always mapped to array
All attributes for which there is cardinality > 1 are always mapped to array
SubmodelElementCollection, Entity etc. is always mapped to map

see also examples in
https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/mappings.html#_examples_value_only_serialization_for_all_submodel_element_types

**Comment by s-heppner** [comment]
Sorry to reopen this issue, but does that influence the schema in any way?

**Comment by BirgitBoss** [comment]
No, it was correct like it is
