### ISSUE TITLE
Optional values for all SubmodelElements

### ISSUE THREAD

**Issue by alexgordtop** [admin-shell-io/aas-specs#412]
The constraints / cardinalities affecting the value of the SubmodelElements are inconsistent.

It is not obvious, why especially ReferenceElement.value, but also Property.value, File.value, Blob.value are optional, but e.g. RelationshipElement.first/second is required.

**Request:**
Please revise required attributes with the aspect of defining a template structure / incomplete model in mind.

----

**Issue caused by restriction:**
This mandatory constraint leads currently to issues with AASX serialization, since some IDTA SubmodelTemplates would like to specify the usage of e.g. RelationshipElements, but when deserializing a corresponding AASX, the parsers will fail according to a xml schema violation.

---

Beside SubmodelTemplates, there are other UseCases, where a kind of requested structure should be provided, that somebody else would have to fill like: 

**Use case:**
A component has an empty configuration, that the operator should fill to configure the asset.
Using RelationshipElements is nearly impossible in the situation.

The same applies to File/Blob.contentType - if a component allows an attachment, it is forced to specify something like "*/*", if it is open for different kinds of values. From a modeler perspective, I would have preferred to not set the contentType in advance and describe in the description, that a kind of image or pdf is accepted as documentation, but no videos.

**Comment by BirgitBoss** [comment]
TF Metamodel 2024-04-17
Discussion not yet finalized but recommendation:
- at least for (Annotated)RelationshipElement make "first" and "second" optional (conformant to min and max of Range)

**Comment by BirgitBoss** [comment]
Decision Proposal TF Part 1 2024-05-15
Besides https://github.com/admin-shell-io/aas-specs/issues/412#issuecomment-2061377393 make the following attributes optional as well:
**File/contentType
Blob/contentType**

Reason:

- contentType may not be fixed at time of creation of a SMT
- even for a Submodel with kind=Instances representing a configuration file that is sent to another stakeholder for filling in the gaps the information might not be available

**Comment by BirgitBoss** [comment]
Workstream AAS Sepc 2024-06-13
accepted
make the following attributes optional

- (Annotated)RelationshipElement/first 
- (Annotated)RelationshipElement/second
- File/contentType
- Blob/contentType
