### ISSUE TITLE
Ordered SubmodelElementCollection in RDF

### ISSUE THREAD

**Issue by kenwenzel** [admin-shell-io/aas-specs#42]
To me it is unclear how ordered `SubmodelElementCollection`s are represented in RDF.

The ontology defines the range of value as `SubModelElement ` (and not as rdf:List or rdfs:Container/rdf:Seq):
https://github.com/admin-shell-io/aas-specs/blob/6ee8a5148153831ac81ff0d8408aad03219a207e/schemas/rdf/rdf-ontology.ttl#L1933

Is there some property on `SubModelElement ` that is used for ordering?

**Comment by changqin26** [comment]
there is another property of **SubmodelElementCollection** called **SubmodelElementCollection/ordered**, it decides whether the elements in a collection is ordered or not.
https://github.com/admin-shell-io/aas-specs/blob/6ee8a5148153831ac81ff0d8408aad03219a207e/schemas/rdf/rdf-ontology.ttl#L1920

**Comment by kenwenzel** [comment]
Yes, the `ordered` property marks the collection as ordered or not. But what is the ordering criterion of the elements?
I see the following solutions for the `ordered=true` case:
- generally use `rdf:List`s as values of `SubmodelElementCollection`s
- use an additional property like `aas:precedes` on the referenced elements and compute a topological ordering
- use a wrapper object like `SubmodelElementCollectionItem` with an additional `index` property that can be used for ordering

**Comment by kenwenzel** [comment]
This is still an issue for draft-C3RC02. It needs to be decided among the possible solutions above.

**Comment by BirgitBoss** [comment]
We now do have two element types: SubmodelElementCollection and SubmodelElementList.

**Comment by mristin** [comment]
Closing since fixed in V3RC02.
