### ISSUE TITLE
Relax Constraint AASD-120 for SMT allow idShort in SML

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#432]
**Is your feature request related to a problem? Please describe.**
For Submodel Template creation it is helpful to have an idShort for the element type within the SML.
This is mainly the case for SML of SMC or SML because there are separate tables for SMC and SML. For properties it is more difficult. 
See discussion in https://github.com/admin-shell-io/submodel-templates/issues/65

`Constraint AASd-120: idShort of submodel elements being a direct child of a SubmodelElementList shall not be specified.`

could be relaxed to

`Constraint AASd-120: idShort of submodel elements being a direct child of a SubmodelElementList shall not be specified within Submodels with kind=Instance.`

**Describe alternatives you've considered**

- do not relax
-- instead create ConceptDescriptions with idShort of the corresponding elements

- remove completely, i.e. also allow idShort in Submodels with kind=Instance for better readability

AASd-120 was a further restriction of
`Constraint AASd-117: idShort of non-identifiable Referables not being a direct child of a SubmodelElementList shall be specified.`

**Comment by BirgitBoss** [comment]
TF Part 1 2024-06-12 Decision Proposal:
remove AASd-120

**Comment by BirgitBoss** [comment]
Accepted in principle by Workstream AAS Spec. 2024-06-13
Comments: 
- within a Submodel with kind=Instance idShorts need to be unique. For SMT there is only exactly one element allowed to be part of the SML.
- However, in idShortPath idShort of SML elements shall not be used (because you cannot rely that the idShort exists)
- In ValueOnly Format of API idShort will not be used (it is an JSON array)
- even consider to make idShort mandatory for SML elements as well (then it could be used in idShortPath as well) However, this is not backward compatible
- Part 2 affected as well, is there a need to add a corresponding comment in Part 2

TF AAS Part 1 will discuss this issue again and make a proposal

**Comment by BirgitBoss** [comment]
2024-07-24 TF Part 1
These constraints are relevant in this context:
`Constraint AASd-117: idShort of non-identifiable Referables not being a direct child of a SubmodelElementList shall be specified.`
`Constraint AASd-120: idShort of submodel elements being a direct child of a SubmodelElementList shall not be specified.`

If AASd-120 is removed then idShort is optional for elements within a SubmodelElementList (SML)

Discussion: shall we request this:
`idShort of an element within a SML shall not be changed`, the position wihtin a SML (the index) might be changed.
Decision: no, although typically an application would not do it

problem: if an element at position with index 3 is deleted, the position of element with index 4 changed to index 3. This would be the normal behavior of an array. However, if two users both want to remove element at index 3 it might happen if the execution requests are very close in time in the end both elements would be removed although this might not have been the intention.

https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/mappings.html#_format_path_idshortpath_serialization_in_json
Discussion: should it be recommended to not use idShort in idShort-Path (since optional) or the opposite: use them if available (because of problem described above)
Decision: no additional note in this chapter

add note to AASd-117: `In Future it might be required that idShort is also mandatory for elements within a SubmodelElementList.`
does this imply that in future also in idShortPath only idShort shall be used? No

**Decision Proposal:**

-  remove AASd-120
- add note to AASd-117: `In future it might be required that idShort is also mandatory for elements within a SubmodelElementList.`
- check formulations in https://admin-shell-io.github.io/aas-specs-antora/IDTA-01001/v3.1/mappings.html#_format_path_idshortpath_serialization_in_json so that both is allowed: idShort and index for elements in SML

**Comment by BirgitBoss** [comment]
@sebbader may you please discuss this issue also in TF Part 2 API whether the impact on the API is accepted. Thank you.

**Comment by sebbader-sap** [comment]
WS AAS Specs (14.11.2024):
Also consider the effect for References that point to SubmodelElements inside SMLs:
```
{
    "type": "ModelReference",
    "keys": [
    {
       "type": "Submdel",
       "value":"http://example.org/my-submodel"
    },
   {
      "type": "SubmdelElementList",
      "value":"smlIdShort"
   },
   {
      "type": "Property",
     "value":"0"    // now a idShort could also appear here
   }
]
}
```

**Comment by sebbader-sap** [comment]
Also appears in this notation:
```
(Submodel)https://example.com/aas/1/1/1234859590, (SubmodelElementList)Documents, (SubmodelElementCollection)0, (MultiLanguageProperty)Title
```

**Comment by mjacoby** [comment]
**Feedback from "Interoperability of Implementations"**

Will affect implementations, but too few participants for significant results.
Trying again on 29.11.

**Comment by mjacoby** [comment]
Actually, we discussed this issue in today's TF meeting and I posted the results on this related issue here https://github.com/admin-shell-io/aas-specs-api/issues/334#issuecomment-2540883953

For simplicity, I will copy my comment here

<blockquote>
Feedback from implementers via TF Interoperability of Implementations:

- the motivating use case (https://github.com/admin-shell-io/submodel-templates/issues/65) seem not really strong and should rather be solved by changing the table to not misuse idShort of type declaration but introduce a `type` field or similar
- implementation would be possible but would require some efforts and maybe even pose a threat/challenge for scalability 
- also sentiment ist that accessing elements in a list/array by something else than the index is very unusual for an API/programming language

The conclusion is that the TF recommends to not go forward with this changes until there is a solid use case/requirement.
</blockquote>

**Comment by BirgitBoss** [comment]
* remove constraint AASd-120
* but do not allow to use idShort in idShortPath
