### ISSUE TITLE
New MimeType requested

### ISSUE THREAD

**Issue by stolze-ifak** [admin-shell-io/aas-specs#453]
We want to add an iCalender file (regarding to RFC 5545) to our AAS. For this we need the mimeType "text/calendar". Can you add it?

Thank you very much.

**Comment by BirgitBoss** [comment]
Since text/calendar is part of RFC 5545 no change of specification needed.

**Comment by BirgitBoss** [comment]
Please feel free to reopen the issue if your concerns are not addressed.

Probably you should raise the issue for the tooling you want to support this mimetype.
