### ISSUE TITLE
[BUG] environment tag should be declared as "xs:element" instead of "xs:group" in AAS.xsd 

### ISSUE THREAD

**Issue by MarcusVonBergen** [admin-shell-io/aas-specs#457]
When validating v3.0 AAS XML files against AAS.xsd I get the error that the tag environment is not declared. Digging deeper 
the error is occurring because in the schema file (XSD), the tag "environment" is defined as an "xs:group" instead of "xs:element" which is supposed to be root. The root element of an XML document should always be defined as an "xs:element" in the XSD file like this in our example:
`<xs:element name="environment">`
Changing the XSD accordingly resolves my validation errors. 
I attached the new XSD file (as txt as GitHub does not support xsd) with the ask to adjust the changes in the project.
[AAS_xsd.txt](https://github.com/user-attachments/files/16361537/AAS_xsd.txt)

**Comment by mristin** [comment]
Thanks, @MarcusVonBergen ! @s-heppner can you please double-check, maybe also with other teams?

All the XSD engines I tested with (Python, C#) worked with the current schema.

**Comment by s-heppner** [comment]
Hi @MarcusVonBergen, can you please tell me which XSD validator you used so that I can try to reproduce the issue?

**Comment by BirgitBoss** [comment]
I do not know but perhaps this is also related to https://github.com/admin-shell-io/aas-test-engines/issues/43? I also get an error when validating an xml file with the test engine

**Comment by s-heppner** [comment]
I do not think this is connected to [admin-shell-io/aas-test-engines#43](https://github.com/admin-shell-io/aas-test-engines/issues/43), since it seems that the XML schema check passes on these files.

**Comment by sebbader-sap** [comment]
> Hi @MarcusVonBergen, can you please tell me which XSD validator you used so that I can try to reproduce the issue?

We are using, for instance, https://www.freeformatter.com/xml-validator-xsd.html and the Visual Studio Code "XML" extension from Red Hat.

**Comment by MarcusVonBergen** [comment]
Hi everyone,
thank you for your quick answers and sorry for my late one. I used an online validator as well as a validation tool that is part of the SAP Integration Suite which builds on top of Apache Camel. Both listed me the same error stating that it cannot find the declaration of the element 'environment' from line 1.
To reproduce the issue do the following:
- Take the AAS XML (I used a v2.0 Bosch example saved it with the AAS Package Explorer to leverage it to v3.0 and resolved the idshort convention changes from v2.0 to v3.0): 
[AAS.xml.txt](https://github.com/user-attachments/files/16470967/AAS.xml.txt)
- This is one of the tools I used to validate the XSD: https://www.freeformatter.com/xml-validator-xsd.html 
- This XSD (currently on GitHub) leads to the error: 
[AAS.xml.txt](https://github.com/user-attachments/files/16471015/AAS.xml.txt)
- This is the modified XSD that defines the environment tag as xs:element. Using this the validation succeeds: 
[AAS_new.xsd.txt](https://github.com/user-attachments/files/16471034/AAS_new.xsd.txt)
I hope I could resolve unclarities.
Kind regards
Marcus

**Comment by mristin** [comment]
(
@mhrimaz can you please create another issue on aas-core-codegen for:
> Note that the SHACL has also another critical issue related to DataSpecificationIec61360.
[SHACL states](https://github.com/aas-core-works/aas-core-codegen/blob/92bcf9ef6301f51f506304f27013f23831238c80/test_data/rdf_shacl/test_main/expected/aas_core_meta.v3/expected_output/shacl-schema.ttl#L786) that a rdf:type aas:LangStringDefinitionTypeIec61360 ; should have the following attribute:
<https://admin-shell.io/aas/3/0/LangStringDefinitionTypeIec61360/text>
However in samples it have <https://admin-shell.io/aas/3/0/AbstractLangString/text>. But this is another issue anyways.

)

**Comment by s-heppner** [comment]
I can confirm that there are XML Schema validators that need the root of an XSD to be an `xs:element`. 
This shouldn't break any other XML Schema validators, as it is valid XSD. 

Therefore, I've adapted the XSD Schema file to include an `xs:element` definition of `aas:environment` in this PR: #464.

@MarcusVonBergen could you please see if the new XSD schema fixes the problems you have?
