### ISSUE TITLE
Clarification request on arbitrary properties/"{arbitrary}" id shorts

### ISSUE THREAD

**Issue by empwilli** [admin-shell-io/aas-specs#459]
The SMT specification of the Digital Nameplate specifies some arbitrary properties with the idShort "{arbitrary}" (e.g. for GuidelineSpecificProperties, or AssetSpecificProperties). My interpretation of these is that these can act as generic placeholders for (in this case) any property type. Unfortunately I was not able to find any clues in the specification to back my interpretation. 

Are there any further rules for these arbitrary types? Can you please clarify/elaborate on arbitrary or point me to additional resources?

**Comment by JoergNeidig** [comment]
This question has been forwarded to SMT "Digital Nameplate" group.

**Comment by JoergNeidig** [comment]
Indeed the {arbitrary} indicates that the user may add properties that are not further defined in the Submodel template. For this the template gives a number of examples, e.g. additional properties for "explosion safety". Therefore, the value type of the properties can be selected as needed (String, Decimal, ...). However, if your question is if any type of SubmodelElement can be used (e.g. File, Range or Blob) then it is safe to assume that only the SubmodelElement property should be used.

**Comment by JoergNeidig** [comment]
Please, also look at "How to create a submodel template": https://industrialdigitaltwin.org/wp-content/uploads/2022/12/I40-IDTA-WS-Process-How-to-write-a-SMT-FINAL-.pdf 
Updates will be posted in https://industrialdigitaltwin.org/content-hub/downloads.

This issue will be closed. Feel free to re-open it if you have additional questions.
