### ISSUE TITLE
Why was Referable/checksum removed?

### ISSUE THREAD

**Issue by JS-Aibel** [admin-shell-io/aas-specs#460]
**Is your feature request related to a problem? Please describe.**
Why has Checksum that was introduced for Referables in version V3.0RC02 been removed in version V3.0?

**Describe the solution you'd like**
When exchanging AASX files, it would be nice to have a standard way of checking if a submodel and its content has been changed.

**Describe alternatives you've considered**
Is there any alternative way of checking if a submodel and its content has been changed within the current mentamodel?

**Comment by JoergNeidig** [comment]
2024-09-04 - AAS Working group
There were too many open questions concerning the implementation of that feature, so we decided to postpone its introduction until these questions have been answered.

This issue will closed. If you have any requirements or solution approaches to the topic of checksums, please feel free to open here a new issue (https://github.com/admin-shell-io/aas-specs-aasx).
