### ISSUE TITLE
Changed Order of `dataSpecificationContent` and `dataSpecification` in XML

### ISSUE THREAD

**Issue by sebbader-sap** [admin-shell-io/aas-specs#477]
**Describe the bug**
[Release v3.0.1](https://github.com/admin-shell-io/aas-specs/commit/87cf203a8c0067cc1315c0fd65c3e1084c11e351#diff-33fa391e7dbbb30b74596de382a4636b499ba32979a3a7e19ebe30afca30626e) has introduced a change also for the attributes `dataSpecificationContent` and `dataSpecification`.

**Where**
The change in order makes every(!) older XML file with embeddedDataSpecifications invalid without any reason.

**Screenshots**
<img width="1182" alt="image" src="https://github.com/user-attachments/assets/b5c04e66-7d27-4c8d-a1d2-aa07e683bb70">

**Proposal**
Given that there is no reason for this change, we could either:
1. revert this change, or
2. change the clause in XML that the order for these two attributes shall not be relevant.

**Comment by BirgitBoss** [comment]
thanks for reporting, will be fixed

**Comment by FrankSchnicke** [comment]
Thanks a lot for addressing this-

However, fixing it by reverting it back to the old ordering may introduce some additional room for incompatibility. Assuming someone started to implement their solution based on the latest release, they would create XML files with the "wrong" order, assuming it is the correct one. After the next release that reverts the ordering, their solution would be creating XML files not in line with the latest XSD.

This scenario is at the moment not very likely but in future I would propose fixing this kind of issues in a way that is compatible to both variants. Here, a possible fix that would not introduce this room for incompatibility would be to allow both orderings.
