### ISSUE TITLE
Add Matching Strategy how to deal with supplementalSemanticID

### ISSUE THREAD

**Issue by J-Blume** [admin-shell-io/aas-specs#479]
**Is your feature request related to a problem? Please describe.**
At the moment it is not described how to handle supplementalSemanticID for the matching of SemanticIDs

**Comment by BirgitBoss** [comment]
2024-10-30 TF AAS Metamodel

Add to Intelligent matching a new group 
   
**Consider Supplemental SemanticId**
   **Strategy 1:** Consider semanticId and supplementatld as a single set of semanticIds
•	Input: set of semanticIds (not distinguishing between semanticId and supplementalIds)
•	Index of supplemantalId is not relevant. SupplematlSemanticId is an unordered list.
•	Match required that **_all_** semanticIds in Input are either in semanticId or in supplementalSemanticIds
•	Include supplemental semanticId when looking for a semanticId that should match. This can be combined with exact or value matching.
•	Example: semanticId xxx would match to supplementalds[3] = xxx
•	Example:  semanticId = xx and supplementatlId[{index}] =yyy does not match semanticId =xx without supplementatIds[{index}] = yy
•	Example:  semanticId = xx and supplementatlId[1] =yyy matches semanticId =xx with supplementatIds[3] = yy
•	Example: Input: {semanticId xxx, semantic yyyy} would not match to semanticId = zzz and supplementalds[3] = xxx
 
  **Strategy 2:** Consider semanticId and supplementatld as a single set of semanticIds
•	Input: set of semanticIds (not distinguishing between semanticId and supplementalIds)
•	Index of supplemantalId is not relevant. SupplematlSemanticId is an unordered list.
•	Match required that **_at least one_** of the semanticIds in Input are either in semanticId or in supplementalSemanticIds
•	Include supplemental semanticId when looking for a semanticId that should match. This can be combined with exact or value matching.
•	Example: semanticId xxx would match to supplementalds[3] = xxx
•	Example: Input: {semanticId xxx, semantic yyyy} would match to supplementalds[3] = xxx


**Consider isCaseOf of referenced semanticId**
**Strategy 1:** extend set semanticIds of **Consider Supplemental SemanticId** to also include isCaseOf 
**Strategy 2:** Input semanticId Consider also isCaseOf
Example: semanticId = xx   matches to semanticId = yy with CD/id = yy and CD/isCaseOf = xx

**Comment by BirgitBoss** [comment]
2024-11-11 Workstream AAS Specs
Decision Proposal accepted https://github.com/admin-shell-io/aas-specs/issues/479#issuecomment-2447596471
