### ISSUE TITLE
Inconsistency between `language` in JSON and `lang` in XML

### ISSUE THREAD

**Issue by mristin** [admin-shell-io/aas-specs#49]
Hi,
I noticed that `langString` is serialized differently in JSON and in XML. In XML, the language property is serialized as `lang`, while in JSON it is written out as `language`. Since the release candidates are still work-in-progress, wouldn't it make sense to make both of those consistent? 

This would make the code generation and/or code annotations easier for the downstream users.

**Comment by BirgitBoss** [comment]
@Manu3756 I think "lang" is the better option. Was there a reason to use language?

**Comment by Manu3756** [comment]
@mristin @BirgitBoss 

I'm fine with changing the JSON serialisation to "lang" with the next release. 

**V3.0RC01** 
langString
```
   {
      "language":"<ISO 3166-1 alpha-2 Country Code>",
      "text":"Some text"
   }
```
langStringSet
```
[
   {
      "language":"<ISO 3166-1 alpha-2 Country Code>",
      "text":"Some text"
   },
   {
      "language":"<ISO 3166-1 alpha-2 Country Code>",
      "text":"Some text"
   }
]
```

**V3.0RC02** 
langString
```
   {
      "lang":"<ISO 3166-1 alpha-2 Country Code>",
      "text":"Some text"
   }
```
langStringSet
```
[
   {
      "lang":"<ISO 3166-1 alpha-2 Country Code>",
      "text":"Some text"
   },
   {
      "lang":"<ISO 3166-1 alpha-2 Country Code>",
      "text":"Ein Text"
   }
]
```
