### ISSUE TITLE
[Shacl | RDF Ontology]: Possible inconsistencies and Questions

### ISSUE THREAD

**Issue by gillistephan** [admin-shell-io/aas-specs#50]
I have been playing around with shacl.ttl and owl.ttl in order to implement a type-generator for Go and Typescript (first generated models for ts can be found [here](https://github.com/gillistephan/aas/tree/main/packages/ts-model/src/lib))

While implementing, some questions came up and possible inconsistencies were detected - 
I [used](https://github.com/admin-shell-io/aas-specs/releases/tag/v3.0.2.RC01) this release.

Regarding __shacl__.ttl:

- (line 1190); aas:ReferableShape --> for property **idShort** _sh:pattern_ is defined twice. should (imo) only be the latter sh:pattern "^[a-zA-Z \w*$"^^xsd:string (following the specs)

- (line 1150); aas:ExtensionShape --> for property **refersTo** _sh:Reference_ is (imo) not a valid vocab in the sh-Namespace. This should probably be replaced with aas:Reference?

- (line 821); aas:KeyShape --> for property **value** _sh:datatype_ is commented out. Is there any specific reason? comparing it to the ont (line 1044), the triple is defined with object value xsd:string.

- (line 729); aas:Formula --> in the ont **aas:Formula** extends **aas:Constraint**. Does this not have to be reflected in shacl? If so, this would imply, that a NodeShape with aas:ConstraintShape needs to be created. 

- line (1142); aas:ExtensionShape --> for property **value** _sh:ValueDataType_ is defined. I couldn't find any definition in the sh-Namespace; Can you please clarify how to interpret this type?

Regarding __owl__.ttl:

- (line 1987 | line 1999); _iec61360:INTEGER_CURRENCY_ is defined twice (probably one should be removed)

**Comment by mristin** [comment]
Hi @gillistephan <https://github.com/gillistephan>,
Please apologize for dropping into the issue. Just FYI: we are working on
generating different schemas (JSON Schema, XSD, RDF, SHACL etc.) from a
meta-model written in a Python subset as well as generating SDKs in
different languages (including Golang and Typescript). Perhaps you want to
have a look (all still work in progress):

https://github.com/aas-core-works/design-docs

https://github.com/aas-core-works/aas-core-meta


https://github.com/aas-core-works/aas-core-csharp-codegen/tree/mristin/Kick-off
(we started with C#, but also generate JSON Schema, RDF and SHACL; this
repository will be split once the initial development has been done)

Perhaps you'd like to help us with the meta-model and then we can release
RDF and SHACL schemas for V3RC2 a bit sooner?

Feel free to contact me over:
https://www.zhaw.ch/en/about-us/person/rist/

**Comment by gillistephan** [comment]
Hi @mristin, 
that sounds interesting. This is basically what I was looking for before starting the implementation. Happy to evaluate if I can help implementing. Will contact you. Cheers S.

**Comment by mristin** [comment]
The issue has been resolved offline over the phone.
