### ISSUE TITLE
BUG: formula_t needs to be mixed xsd type

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#51]
Problem: Goal ist to express a formula like this:

<aas:Formula>
   <aas:dependsOn>
         <Keys> 	 <Key type=”Submodel”>https://myShell/Machine</Key>
			 <Key type=”Property”>Status</Key>
   </aas:dependsOn>  != RUNNING
</aas:Formula>

Therefore

<complexType name="formula_t">
		<sequence>
			<element maxOccurs="1" minOccurs="0" name="dependsOnRefs" type="aas:references_t"/>
		</sequence>
</complexType

==> mixed=true and fix sequence

<complexType name="formula_t" mixed="true">
		<sequence>
			<element maxOccurs="1" minOccurs="unbounded" name="dependsOnRef" type="aas:reference_t"/>
		</sequence>
	</complexType

compare to Example in https://www.informit.com/articles/article.aspx?p=31530&seqNum=5

**Comment by mristin** [comment]
Closing since the security part has been removed. This is reflected in #204.
