### ISSUE TITLE
xml serialization: DataSpecificationPhysicalUnit is missing

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#53]
DataSpecificationPhysicalUnit (introduced in V2.0) is not yet serialized.

Add new file 
dataSpecification_IEC61360_PhysicalUnit.xsd
with its specification.

Add data specification in complexType dataSpecificationContent as Choice

<complexType name="dataSpecificationContent_t">
		<choice>
			<element name="dataSpecificationIEC61360" type="IEC61360:dataSpecificationIEC61630_t"/>
                        <element name="dataSpecificationPhysicalUnit" type="IEC61360:dataSpecificationPhysicalUnit_t"/>
		</choice>
	</complexType>
and import it:
	<import namespace="http://www.admin-shell.io/IEC61360PhysicalUnit/3/0/RC02" schemaLocation="IEC61360.xsd"/>

Its global id is:
https://admin-shell.io/DataSpecificationTemplates/DataSpecificationTemplates/DataSpecificationPhysicalUnit/1/0” 

Later it should be thought about to restrict the data specification to the elements they can be applied to, in this case to ConceptDescriptions only.

**Comment by mristin** [comment]
Closing since fixed in #204.
