### ISSUE TITLE
XML HasSemantics, max 1 semanticId - make explicit

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#54]
<group name="hasSemantics">
		<sequence>
			<element minOccurs="0" name="semanticId" type="aas:semanticId_t"/>
		</sequence>
	</group>

==> max=1

	<group name="hasSemantics">
		<sequence>
			<element minOccurs="0" maxOccurs="1" name="semanticId" type="aas:semanticId_t"/>
		</sequence>
	</group>

**Comment by mristin** [comment]
Closing since fixed in #204.
