### ISSUE TITLE
Different versions of JSON examples

### ISSUE THREAD

**Issue by markus-ap** [admin-shell-io/aas-specs#62]
[test_demo_full_example.json](https://github.com/admin-shell-io/aas-specs/blob/master/schemas/json/examples/test_demo_full_example.json) and [jsonExample.json](https://github.com/admin-shell-io/aas-specs/blob/master/schemas/json/examples/jsonExample.json) both appear to be from commits that update JSON to `V3.0RC01`, but they are using different versions of AAS.

`test_demo_full_example.json`, for example, uses `Asset/assetIdentificationModel` which was removed in `V3.0RC01` per [Part 1 V3](https://www.plattform-i40.de/IP/Redaktion/EN/Downloads/Publikation/Details_of_the_Asset_Administration_Shell_Part1_V3.pdf?__blob=publicationFile&v=5). 

Would be useful to either have them both use the same version of AAS, or have it made more clear which version each example is on.
It is especially confusing seeing how `test_demo_full_example.json` was pushed a while after `jsonExample.json`.

**Comment by BirgitBoss** [comment]
@g1zzm0 will you please have a look? In the moment the goal is to have V3.0RC01 with its examples, make a release update and then update to V3.0RC02.

**Comment by g1zzm0** [comment]
@Manu3756 @sebbader updated the examples to V3.0RC01 with the commits #35 and #13

**Comment by markus-ap** [comment]
It seems that commit fixes it, but has not made its way to the master branch as Asset/assetIdentificationModel is still present in [master](https://github.com/admin-shell-io/aas-specs/blob/master/schemas/json/examples/test_demo_full_example.json). Line 2523.

**Comment by Manu3756** [comment]
This looks like a bug in the JSON examples. 
The examples and the schema will be updated with V3.0RC02.

**Comment by g1zzm0** [comment]
Is it possible to fix the bug in the JSON examples in the updated Version of V3.0RC01?

**Comment by Manu3756** [comment]
I fixed it in the master. I am not sure if it is worth a new release. I recommend to do a final release before we start with V3.0RC02.
