### ISSUE TITLE
JSON Mapping of HasDataSpecification | List of Reference vs single Reference element

### ISSUE THREAD

**Issue by markus-ap** [admin-shell-io/aas-specs#63]
In the [Details of the Asset Administration Shell Part1 (V3)](https://www.plattform-i40.de/IP/Redaktion/EN/Downloads/Publikation/Details_of_the_Asset_Administration_Shell_Part1_V3.pdf?__blob=publicationFile&v=5) document, on page 60, the abstract class `HasDataSpecification` is described has having one attribute, `dataSpecification`, which is a list of elements of the type `Reference`.

In the json serialisation examples there are instances where the `dataSpecification` is instead not a list, but a single element of the type `Reference`.

I am unsure if this is by design, or by human error.

Excerpt from [jsonExample.json](https://github.com/admin-shell-io/aas-specs/blob/master/schemas/json/examples/jsonExample.json#L491):
```json
"embeddedDataSpecifications": [
            {
               "dataSpecification": {
                  "keys": [
                     {
                        "type": "GlobalReference",
                        "value": "http://adminshell.io/DataSpecificationTemplates/DataSpecificationIEC61360",
                        "idType": "IRI"
                     }
                  ]
               },
```

My understanding of the documentation and schema is that it should be like the following.
```json
"embeddedDataSpecifications": [
            {
               "dataSpecification": [{
                  "keys": [
                     {
                        "type": "GlobalReference",
                        "value": "http://adminshell.io/DataSpecificationTemplates/DataSpecificationIEC61360",
                        "idType": "IRI"
                     }
                  ]
               }],
```

I would have submitted a pull request, but I am not confident that I have not misunderstood something regarding this.

Edit:
It seems the schema is also using arrays/lists rather than single elements, as seen in [aas.json](https://github.com/admin-shell-io/aas-specs/blob/master/schemas/json/aas.json#L111-L121).

**Comment by BirgitBoss** [comment]
To me the current example looks correct, I extend it with a second data specification:

"embeddedDataSpecifications": [
            {
               "dataSpecification": {
                  "keys": [
                     {
                        "type": "GlobalReference",
                        "value": "http://adminshell.io/DataSpecificationTemplates/DataSpecificationIEC61360",
                        "idType": "IRI"
                     }
                  ]
               },
            {
               "dataSpecification": {
                  "keys": [
                     {
                        "type": "GlobalReference",
                        "value": "http://adminshell.io/DataSpecificationTemplates/AnotherDataSpec",
                        "idType": "IRI"
                     }
                  ]
               }],

@Manu3756 : please check

**Comment by markus-ap** [comment]
The problem I am referring to is the attribute "dataSpecification" being described as having 0 to many Reference objects.

I had imagined this being easily implemented with "dataSpecification" being serialised as a list of Reference objects, but in the json example there is instead just one singular Reference object.

```cs
public List<Reference> dataSpecification
```

It would at least make serialisation and deserialisation quite trouble free.

**Comment by Manu3756** [comment]
@markus-ap 

This is a specific rule for JSON serialisation. See: [README.md Rule 5]( https://github.com/admin-shell-io/aas-specs/blob/master/schemas/json/README.md )

> "Data Specification Templates are directly added to the Concept Description. Additionally, a new element EmbeddedDataSpecification is introduced that has two attributes: one for the global reference to the data specification identifier and one for the content of the data specification."

Instead of having a list of references and no content, we decided to introduce a new object called **embeddedDataSpecifications**. So the attribute dataSpecifcation in UML is renamed to embeddedDataSpecifications in JSON and an additional attribute dataSpecificationContent is added in JSON as well.

So in UML it is like that: 

```JAVA
public List<Reference> dataSpecification

```


In JSON it is like that: 

```JAVA
List<EmbeddedDataSpecification> embeddedDataSpecification

public class EmbeddedDataSpecification {
  public Reference dataSpectification;
  public DataSpecificationContent dataSpecificationContent;
}
```

I agree that we should align the UML with the serialisation for V3.0RC02.

**Comment by mristin** [comment]
Closing the issue as this has been documented in the book Section 9.2.5.
