### ISSUE TITLE
Update Contribution Guide - assign PR to Issue

### ISSUE THREAD

**Issue by BirgitBoss** [admin-shell-io/aas-specs#78]
For preparation to do more and more specification in github itself (up to now published pdf of the specification was the master) we need to have a stringent coupling of issues and PRs. This is the proposal for the update of the current **Create Pull Request** SubChapter (in the moment it is recommended to prefix with profile name, e.g. BirgitBoss/myNewFeature:

### Create Pull Request

Proposals for changes to the content of the repository are managed through Pull Requests (PRs).

To open such a PR, implement the changes in a new feature branch. Each PR must reference an issue and follows the naming schema: <issue-number>-<feature-name>. For a new PR the target branch is the main branch while the source branch is your feature branch The feature branch branch should be developed in a fork of the upstream repository. So before working on your first feature, you need to create such a fork (e.g., by pressing the Fork button in the top right corner of the GitHub page)

When opening a PR please consider the following topics:

    - optional: Rebase your development on the branch to which you plan to create the PR.
    - Each PR must be linked to an Issue:
        Reference the Issue number in the name of your feature branch and the description of the PR.
        Mention the Issue in one of the commit messages associated to the PR together with a GitHub keyword like closes #IssueNumber or fixes #IssuesNumber. For more details visit the GitHub documentation on linking PR with Issues
    - Each PR should only contain changes related to a single work item. If the changes cover more than one work item or feature, then create one PR per work item. You may need to create new more specific Issues to reference if you split up the work into multiple feature branches.
    - Commit changes often. A PR may contain one or more commits.

**Comment by g1zzm0** [comment]
This is not an Issue, but a very good change request. Please feel free to make a commit with s follow-up PR for this particular change.

**Comment by BirgitBoss** [comment]
Every change needs an issue. But this is exactly the scope of the issue to define these rules.
